# coding: utf-8

"""
    Floor Memory

    The set APIs are used to develop Floor pds which can be used as their personal assistants.   This set of APIs are divided into two parts.  - Memory and  - Registration.   The developer has two ways of using the APIs for the app development. Developer can choose to the  Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ipomo.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xfloor_memory_sdk.models.edit_floor400_response_error import EditFloor400ResponseError

class TestEditFloor400ResponseError(unittest.TestCase):
    """EditFloor400ResponseError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EditFloor400ResponseError:
        """Test EditFloor400ResponseError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EditFloor400ResponseError`
        """
        model = EditFloor400ResponseError()
        if include_optional:
            return EditFloor400ResponseError(
                code = '',
                message = '',
                path = '',
                timestamp = ''
            )
        else:
            return EditFloor400ResponseError(
                code = '',
                message = '',
                path = '',
                timestamp = '',
        )
        """

    def testEditFloor400ResponseError(self):
        """Test EditFloor400ResponseError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
