# coding: utf-8

"""
    Floor Memory

    The set APIs are used to develop Floor pds which can be used as their personal assistants.   This set of APIs are divided into two parts.  - Memory and  - Registration.   The developer has two ways of using the APIs for the app development. Developer can choose to the  Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ipomo.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xfloor_memory_sdk.models.sign_in_response import SignInResponse

class TestSignInResponse(unittest.TestCase):
    """SignInResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignInResponse:
        """Test SignInResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignInResponse`
        """
        model = SignInResponse()
        if include_optional:
            return SignInResponse(
                profile = xfloor_memory_sdk.models.user_details_profile.UserDetails_profile(
                    floor_id = '', 
                    floor_count_info = xfloor_memory_sdk.models.remaining.Remaining(
                        permitted = '', 
                        remaining = '', ), 
                    block_count_info = xfloor_memory_sdk.models.remaining.Remaining(
                        permitted = '', 
                        remaining = '', ), 
                    fid = '', 
                    title = '', 
                    name = '', 
                    email = '', 
                    mobile_number = '', 
                    user_id = '', 
                    avatar = xfloor_memory_sdk.models.user_details_profile_avatar.UserDetails_profile_avatar(
                        url = '', 
                        type = '', ), ),
                pod_info = xfloor_memory_sdk.models.user_details_pod_info.UserDetails_pod_info(
                    floor_id = '', 
                    is_owner = '', 
                    app_id = '', 
                    title = '', 
                    details = '', 
                    floor_uid = '', 
                    blocks = [
                        xfloor_memory_sdk.models.block_details.BlockDetails(
                            block_id = '', 
                            type = '', 
                            title = '', )
                        ], 
                    avatar = xfloor_memory_sdk.models.media.Media(
                        url = '', 
                        type = '', ), ),
                app_id = ''
            )
        else:
            return SignInResponse(
                profile = xfloor_memory_sdk.models.user_details_profile.UserDetails_profile(
                    floor_id = '', 
                    floor_count_info = xfloor_memory_sdk.models.remaining.Remaining(
                        permitted = '', 
                        remaining = '', ), 
                    block_count_info = xfloor_memory_sdk.models.remaining.Remaining(
                        permitted = '', 
                        remaining = '', ), 
                    fid = '', 
                    title = '', 
                    name = '', 
                    email = '', 
                    mobile_number = '', 
                    user_id = '', 
                    avatar = xfloor_memory_sdk.models.user_details_profile_avatar.UserDetails_profile_avatar(
                        url = '', 
                        type = '', ), ),
                pod_info = xfloor_memory_sdk.models.user_details_pod_info.UserDetails_pod_info(
                    floor_id = '', 
                    is_owner = '', 
                    app_id = '', 
                    title = '', 
                    details = '', 
                    floor_uid = '', 
                    blocks = [
                        xfloor_memory_sdk.models.block_details.BlockDetails(
                            block_id = '', 
                            type = '', 
                            title = '', )
                        ], 
                    avatar = xfloor_memory_sdk.models.media.Media(
                        url = '', 
                        type = '', ), ),
        )
        """

    def testSignInResponse(self):
        """Test SignInResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
