# coding: utf-8

"""
    Floor Memory

    The set APIs are used to develop Floor pds which can be used as their personal assistants.   This set of APIs are divided into two parts.  - Memory and  - Registration.   The developer has two ways of using the APIs for the app development. Developer can choose to the  Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ipomo.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xfloor_memory_sdk.models.query422_response import Query422Response

class TestQuery422Response(unittest.TestCase):
    """Query422Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Query422Response:
        """Test Query422Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Query422Response`
        """
        model = Query422Response()
        if include_optional:
            return Query422Response(
                error = xfloor_memory_sdk.models.query_422_response_error.query_422_response_error(
                    message = '', )
            )
        else:
            return Query422Response(
                error = xfloor_memory_sdk.models.query_422_response_error.query_422_response_error(
                    message = '', ),
        )
        """

    def testQuery422Response(self):
        """Test Query422Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
