# coding: utf-8

"""
    Floor Memory

    The set APIs are used to develop Floor pds which can be used as their personal assistants.   This set of APIs are divided into two parts.  - Memory and  - Registration.   The developer has two ways of using the APIs for the app development. Developer can choose to the  Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ipomo.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xfloor_memory_sdk.models.change_email200_response import ChangeEmail200Response

class TestChangeEmail200Response(unittest.TestCase):
    """ChangeEmail200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChangeEmail200Response:
        """Test ChangeEmail200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChangeEmail200Response`
        """
        model = ChangeEmail200Response()
        if include_optional:
            return ChangeEmail200Response(
                profile = xfloor_memory_sdk.models.change_email_200_response_profile.changeEmail_200_response_profile(
                    floor_id = '', 
                    floor_count_info = xfloor_memory_sdk.models.remaining.Remaining(
                        permitted = '', 
                        remaining = '', ), 
                    block_count_info = xfloor_memory_sdk.models.remaining.Remaining(
                        permitted = '', 
                        remaining = '', ), 
                    fid = '', 
                    name = '', 
                    email = '', 
                    mobile_number = '', 
                    user_id = '', 
                    avatar = xfloor_memory_sdk.models.change_email_200_response_profile_avatar.changeEmail_200_response_profile_avatar(
                        url = '', 
                        id = '', ), ),
                pod_info = xfloor_memory_sdk.models.change_email_200_response_pod_info.changeEmail_200_response_pod_info(
                    floor_id = '', 
                    is_owner = '', 
                    app_id = '', 
                    title = '', 
                    details = '', 
                    floor_uid = '', 
                    blocks = [
                        xfloor_memory_sdk.models.block_details.BlockDetails(
                            block_id = '', 
                            type = '', 
                            title = '', )
                        ], 
                    avatar = xfloor_memory_sdk.models.media.Media(
                        url = '', 
                        type = '', ), ),
                app_id = ''
            )
        else:
            return ChangeEmail200Response(
                profile = xfloor_memory_sdk.models.change_email_200_response_profile.changeEmail_200_response_profile(
                    floor_id = '', 
                    floor_count_info = xfloor_memory_sdk.models.remaining.Remaining(
                        permitted = '', 
                        remaining = '', ), 
                    block_count_info = xfloor_memory_sdk.models.remaining.Remaining(
                        permitted = '', 
                        remaining = '', ), 
                    fid = '', 
                    name = '', 
                    email = '', 
                    mobile_number = '', 
                    user_id = '', 
                    avatar = xfloor_memory_sdk.models.change_email_200_response_profile_avatar.changeEmail_200_response_profile_avatar(
                        url = '', 
                        id = '', ), ),
                pod_info = xfloor_memory_sdk.models.change_email_200_response_pod_info.changeEmail_200_response_pod_info(
                    floor_id = '', 
                    is_owner = '', 
                    app_id = '', 
                    title = '', 
                    details = '', 
                    floor_uid = '', 
                    blocks = [
                        xfloor_memory_sdk.models.block_details.BlockDetails(
                            block_id = '', 
                            type = '', 
                            title = '', )
                        ], 
                    avatar = xfloor_memory_sdk.models.media.Media(
                        url = '', 
                        type = '', ), ),
        )
        """

    def testChangeEmail200Response(self):
        """Test ChangeEmail200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
