# coding: utf-8

"""
    Floor Memory

    The set APIs are used to develop Floor pds which can be used as their personal assistants.   This set of APIs are divided into two parts.  - Memory and  - Registration.   The developer has two ways of using the APIs for the app development. Developer can choose to the  Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ipomo.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xfloor_memory_sdk.models.sign_in_with_email200_response_profile import SignInWithEmail200ResponseProfile

class TestSignInWithEmail200ResponseProfile(unittest.TestCase):
    """SignInWithEmail200ResponseProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignInWithEmail200ResponseProfile:
        """Test SignInWithEmail200ResponseProfile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignInWithEmail200ResponseProfile`
        """
        model = SignInWithEmail200ResponseProfile()
        if include_optional:
            return SignInWithEmail200ResponseProfile(
                floor_id = '',
                fid = '',
                blocks = [
                    xfloor_memory_sdk.models.block_details.BlockDetails(
                        bid = '', 
                        type = '', 
                        title = '', )
                    ],
                name = '',
                email = '',
                mobile_number = '',
                user_id = '',
                avatar = xfloor_memory_sdk.models.sign_in_with_email_200_response_profile_avatar.signInWithEmail_200_response_profile_avatar(
                    url = '', 
                    id = '', )
            )
        else:
            return SignInWithEmail200ResponseProfile(
                floor_id = '',
                fid = '',
                user_id = '',
        )
        """

    def testSignInWithEmail200ResponseProfile(self):
        """Test SignInWithEmail200ResponseProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
