# coding: utf-8

"""
    Floor Memory

    The set APIs are used to develop Floor pds which can be used as their personal assistants.   This set of APIs are divided into two parts.  - Memory and  - Registration.   The developer has two ways of using the APIs for the app development. Developer can choose to the  Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ipomo.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xfloor_memory_sdk.models.get_conversations200_response_conversation_inner import GetConversations200ResponseConversationInner

class TestGetConversations200ResponseConversationInner(unittest.TestCase):
    """GetConversations200ResponseConversationInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetConversations200ResponseConversationInner:
        """Test GetConversations200ResponseConversationInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetConversations200ResponseConversationInner`
        """
        model = GetConversations200ResponseConversationInner()
        if include_optional:
            return GetConversations200ResponseConversationInner(
                user = xfloor_memory_sdk.models.get_conversations_200_response_conversation_inner_user.getConversations_200_response_conversation_inner_user(
                    context = xfloor_memory_sdk.models.get_conversations_200_response_conversation_inner_user_context.getConversations_200_response_conversation_inner_user_context(
                        floor_id = '', 
                        title = '', 
                        fid = '', 
                        floor_category = '', 
                        floor_mode = '', ), 
                    user_query = '', 
                    user_id = '', 
                    user_thread = '', 
                    recorded_content = '', ),
                assistant = xfloor_memory_sdk.models.get_conversations_200_response_conversation_inner_assistant.getConversations_200_response_conversation_inner_assistant(
                    id = '', 
                    object = '', 
                    created = 56, 
                    floor_mode = '', 
                    model = '', 
                    choices = [
                        xfloor_memory_sdk.models.get_conversations_200_response_conversation_inner_assistant_choices_inner.getConversations_200_response_conversation_inner_assistant_choices_inner(
                            index = 56, 
                            message = xfloor_memory_sdk.models.get_conversations_200_response_conversation_inner_assistant_choices_inner_message.getConversations_200_response_conversation_inner_assistant_choices_inner_message(
                                role = '', 
                                content = '', ), 
                            finish_reason = '', 
                            ai_model_details = xfloor_memory_sdk.models.get_conversations_200_response_conversation_inner_assistant_choices_inner_ai_model_details.getConversations_200_response_conversation_inner_assistant_choices_inner_ai_model_details(
                                top_p = '', 
                                output_choice = '', 
                                frequency_penalty = '', 
                                max_tokens = '', 
                                presence_penalty = '', 
                                temperature = '', 
                                model = '', 
                                model_id = '', ), 
                            prompt_details = xfloor_memory_sdk.models.get_conversations_200_response_conversation_inner_assistant_choices_inner_prompt_details.getConversations_200_response_conversation_inner_assistant_choices_inner_prompt_details(
                                system_prompt_id = '', 
                                system_prompt = '', ), )
                        ], 
                    fetch_multiple_posts = xfloor_memory_sdk.models.get_conversations_200_response_conversation_inner_assistant_fetch_multiple_posts.getConversations_200_response_conversation_inner_assistant_fetch_multiple_posts(
                        content_type = '', 
                        query = '', 
                        status = '', 
                        message = '', 
                        results = [
                            xfloor_memory_sdk.models.get_conversations_200_response_conversation_inner_assistant_fetch_multiple_posts_results_inner.getConversations_200_response_conversation_inner_assistant_fetch_multiple_posts_results_inner(
                                from_floor = '', 
                                content = '', 
                                author = '', 
                                block_type = 56, 
                                pid = '', 
                                bid = '', 
                                fid = '', 
                                score = 1.337, 
                                match_type = '', )
                            ], ), 
                    content_type = '', )
            )
        else:
            return GetConversations200ResponseConversationInner(
        )
        """

    def testGetConversations200ResponseConversationInner(self):
        """Test GetConversations200ResponseConversationInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
