# coding: utf-8

# flake8: noqa
"""
    Floor Memory

    The set APIs are used to develop Floor pds which can be used as their personal assistants.   This set of APIs are divided into two parts.  - Memory and  - Registration.   The developer has two ways of using the APIs for the app development. Developer can choose to the  Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ipomo.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from xfloor_memory_sdk.models.block_details import BlockDetails
from xfloor_memory_sdk.models.change_password200_response import ChangePassword200Response
from xfloor_memory_sdk.models.edit_floor400_response import EditFloor400Response
from xfloor_memory_sdk.models.edit_floor400_response_error import EditFloor400ResponseError
from xfloor_memory_sdk.models.event400_response import Event400Response
from xfloor_memory_sdk.models.event400_response_error import Event400ResponseError
from xfloor_memory_sdk.models.event_response import EventResponse
from xfloor_memory_sdk.models.floor_info import FloorInfo
from xfloor_memory_sdk.models.get_floor_information200_response import GetFloorInformation200Response
from xfloor_memory_sdk.models.get_recent_events200_response import GetRecentEvents200Response
from xfloor_memory_sdk.models.get_recent_events200_response_items_inner import GetRecentEvents200ResponseItemsInner
from xfloor_memory_sdk.models.get_recent_events200_response_items_inner_author import GetRecentEvents200ResponseItemsInnerAuthor
from xfloor_memory_sdk.models.get_recent_events400_response import GetRecentEvents400Response
from xfloor_memory_sdk.models.get_recent_events400_response_error import GetRecentEvents400ResponseError
from xfloor_memory_sdk.models.media import Media
from xfloor_memory_sdk.models.model400_error_code import Model400ErrorCode
from xfloor_memory_sdk.models.query422_response import Query422Response
from xfloor_memory_sdk.models.query422_response_error import Query422ResponseError
from xfloor_memory_sdk.models.query_request import QueryRequest
from xfloor_memory_sdk.models.query_request_filters import QueryRequestFilters
from xfloor_memory_sdk.models.query_response import QueryResponse
from xfloor_memory_sdk.models.query_response_items_inner import QueryResponseItemsInner
from xfloor_memory_sdk.models.reset_password200_response import ResetPassword200Response
from xfloor_memory_sdk.models.reset_password400_response import ResetPassword400Response
from xfloor_memory_sdk.models.send_validation_code200_response import SendValidationCode200Response
from xfloor_memory_sdk.models.send_validation_code_request import SendValidationCodeRequest
from xfloor_memory_sdk.models.sign_in_with_email200_response import SignInWithEmail200Response
from xfloor_memory_sdk.models.sign_in_with_email200_response_pod_info import SignInWithEmail200ResponsePodInfo
from xfloor_memory_sdk.models.sign_in_with_email200_response_profile import SignInWithEmail200ResponseProfile
from xfloor_memory_sdk.models.sign_in_with_email200_response_profile_avatar import SignInWithEmail200ResponseProfileAvatar
from xfloor_memory_sdk.models.sign_up200_response import SignUp200Response
from xfloor_memory_sdk.models.sign_up_response import SignUpResponse
from xfloor_memory_sdk.models.user_details import UserDetails
from xfloor_memory_sdk.models.validate_code400_response import ValidateCode400Response
from xfloor_memory_sdk.models.validate_code400_response_error import ValidateCode400ResponseError
from xfloor_memory_sdk.models.validate_code412_response import ValidateCode412Response
from xfloor_memory_sdk.models.validate_code_request import ValidateCodeRequest

