# coding: utf-8

"""
    Floor Memory

    The set APIs are used to develop Floor pds which can be used as their personal assistants. This set of APIs are divided into two parts.
    - Memory and
    - Registration. The developer has two ways of using the APIs for the app development. Developer can choose to the Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ipomo.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from xfloor_memory_sdk.models.get_conversations200_response_conversation_inner_assistant_choices_inner_ai_model_details import GetConversations200ResponseConversationInnerAssistantChoicesInnerAiModelDetails
from xfloor_memory_sdk.models.get_conversations200_response_conversation_inner_assistant_choices_inner_message import GetConversations200ResponseConversationInnerAssistantChoicesInnerMessage
from xfloor_memory_sdk.models.get_conversations200_response_conversation_inner_assistant_choices_inner_prompt_details import GetConversations200ResponseConversationInnerAssistantChoicesInnerPromptDetails
from typing import Optional, Set
from typing_extensions import Self

class GetConversations200ResponseConversationInnerAssistantChoicesInner(BaseModel):
    """
    GetConversations200ResponseConversationInnerAssistantChoicesInner
    """ # noqa: E501
    index: Optional[StrictInt] = None
    message: Optional[GetConversations200ResponseConversationInnerAssistantChoicesInnerMessage] = None
    finish_reason: Optional[StrictStr] = None
    ai_model_details: Optional[GetConversations200ResponseConversationInnerAssistantChoicesInnerAiModelDetails] = None
    prompt_details: Optional[GetConversations200ResponseConversationInnerAssistantChoicesInnerPromptDetails] = None
    __properties: ClassVar[List[str]] = ["index", "message", "finish_reason", "ai_model_details", "prompt_details"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetConversations200ResponseConversationInnerAssistantChoicesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of message
        if self.message:
            _dict['message'] = self.message.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ai_model_details
        if self.ai_model_details:
            _dict['ai_model_details'] = self.ai_model_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of prompt_details
        if self.prompt_details:
            _dict['prompt_details'] = self.prompt_details.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetConversations200ResponseConversationInnerAssistantChoicesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "index": obj.get("index"),
            "message": GetConversations200ResponseConversationInnerAssistantChoicesInnerMessage.from_dict(obj["message"]) if obj.get("message") is not None else None,
            "finish_reason": obj.get("finish_reason"),
            "ai_model_details": GetConversations200ResponseConversationInnerAssistantChoicesInnerAiModelDetails.from_dict(obj["ai_model_details"]) if obj.get("ai_model_details") is not None else None,
            "prompt_details": GetConversations200ResponseConversationInnerAssistantChoicesInnerPromptDetails.from_dict(obj["prompt_details"]) if obj.get("prompt_details") is not None else None
        })
        return _obj


