# coding: utf-8

"""
    Floor Memory

    The set APIs are used to develop Floor pds which can be used as their personal assistants. This set of APIs are divided into two parts.
    - Memory and
    - Registration. The developer has two ways of using the APIs for the app development. Developer can choose to the Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ipomo.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from xfloor_memory_sdk.models.get_conversations200_response_conversation_inner_assistant_choices_inner import GetConversations200ResponseConversationInnerAssistantChoicesInner
from xfloor_memory_sdk.models.get_conversations200_response_conversation_inner_assistant_fetch_multiple_posts import GetConversations200ResponseConversationInnerAssistantFetchMultiplePosts
from typing import Optional, Set
from typing_extensions import Self

class GetConversations200ResponseConversationInnerAssistant(BaseModel):
    """
    GetConversations200ResponseConversationInnerAssistant
    """ # noqa: E501
    id: StrictStr
    object: StrictStr
    created: StrictInt
    floor_mode: StrictStr
    model: StrictStr
    choices: List[GetConversations200ResponseConversationInnerAssistantChoicesInner]
    fetch_multiple_posts: GetConversations200ResponseConversationInnerAssistantFetchMultiplePosts
    content_type: StrictStr
    __properties: ClassVar[List[str]] = ["id", "object", "created", "floor_mode", "model", "choices", "fetch_multiple_posts", "content_type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetConversations200ResponseConversationInnerAssistant from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in choices (list)
        _items = []
        if self.choices:
            for _item_choices in self.choices:
                if _item_choices:
                    _items.append(_item_choices.to_dict())
            _dict['choices'] = _items
        # override the default output from pydantic by calling `to_dict()` of fetch_multiple_posts
        if self.fetch_multiple_posts:
            _dict['fetch_multiple_posts'] = self.fetch_multiple_posts.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetConversations200ResponseConversationInnerAssistant from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "object": obj.get("object"),
            "created": obj.get("created"),
            "floor_mode": obj.get("floor_mode"),
            "model": obj.get("model"),
            "choices": [GetConversations200ResponseConversationInnerAssistantChoicesInner.from_dict(_item) for _item in obj["choices"]] if obj.get("choices") is not None else None,
            "fetch_multiple_posts": GetConversations200ResponseConversationInnerAssistantFetchMultiplePosts.from_dict(obj["fetch_multiple_posts"]) if obj.get("fetch_multiple_posts") is not None else None,
            "content_type": obj.get("content_type")
        })
        return _obj


