/*
 * Floor Memory
 * The set APIs are used to develop Floor pds which can be used as their personal assistants.   This set of APIs are divided into two parts.  - Memory and  - Registration.   The developer has two ways of using the APIs for the app development. Developer can choose to the  Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ipomo.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.xfloor.memory.model;

import ai.xfloor.memory.model.Event400ResponseError;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Event400Response
 */
public class Event400ResponseTest {
    private final Event400Response model = new Event400Response();

    /**
     * Model tests for Event400Response
     */
    @Test
    public void testEvent400Response() {
        // TODO: test Event400Response
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

}
