/*
 * Floor Memory
 * The set APIs are used to develop Floor pds which can be used as their personal assistants.   This set of APIs are divided into two parts.  - Memory and  - Registration.   The developer has two ways of using the APIs for the app development. Developer can choose to the  Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ipomo.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.xfloor.memory.model;

import ai.xfloor.memory.model.Media;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetRecentEvents200ResponseItemsInnerAuthor
 */
public class GetRecentEvents200ResponseItemsInnerAuthorTest {
    private final GetRecentEvents200ResponseItemsInnerAuthor model = new GetRecentEvents200ResponseItemsInnerAuthor();

    /**
     * Model tests for GetRecentEvents200ResponseItemsInnerAuthor
     */
    @Test
    public void testGetRecentEvents200ResponseItemsInnerAuthor() {
        // TODO: test GetRecentEvents200ResponseItemsInnerAuthor
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'floorId'
     */
    @Test
    public void floorIdTest() {
        // TODO: test floorId
    }

    /**
     * Test the property 'avatar'
     */
    @Test
    public void avatarTest() {
        // TODO: test avatar
    }

    /**
     * Test the property 'floorUid'
     */
    @Test
    public void floorUidTest() {
        // TODO: test floorUid
    }

}
