/*
 * Floor Memory
 * The set APIs are used to develop Floor pds which can be used as their personal assistants. This set of APIs are divided into two parts.
 * - Memory and
 * - Registration. The developer has two ways of using the APIs for the app development. Developer can choose to the Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ipomo.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.xfloor.memory.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.xfloor.memory.client.JSON;

/**
 * GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner {
  public static final String SERIALIZED_NAME_FROM_FLOOR = "from_floor";
  @SerializedName(SERIALIZED_NAME_FROM_FLOOR)
  @javax.annotation.Nonnull
  private String fromFloor;

  public static final String SERIALIZED_NAME_CONTENT = "content";
  @SerializedName(SERIALIZED_NAME_CONTENT)
  @javax.annotation.Nonnull
  private String content;

  public static final String SERIALIZED_NAME_AUTHOR = "author";
  @SerializedName(SERIALIZED_NAME_AUTHOR)
  @javax.annotation.Nonnull
  private String author;

  public static final String SERIALIZED_NAME_BLOCK_TYPE = "block_type";
  @SerializedName(SERIALIZED_NAME_BLOCK_TYPE)
  @javax.annotation.Nonnull
  private Integer blockType;

  public static final String SERIALIZED_NAME_PID = "pid";
  @SerializedName(SERIALIZED_NAME_PID)
  @javax.annotation.Nonnull
  private String pid;

  public static final String SERIALIZED_NAME_BID = "bid";
  @SerializedName(SERIALIZED_NAME_BID)
  @javax.annotation.Nonnull
  private String bid;

  public static final String SERIALIZED_NAME_FID = "fid";
  @SerializedName(SERIALIZED_NAME_FID)
  @javax.annotation.Nonnull
  private String fid;

  public static final String SERIALIZED_NAME_SCORE = "score";
  @SerializedName(SERIALIZED_NAME_SCORE)
  @javax.annotation.Nonnull
  private BigDecimal score;

  public static final String SERIALIZED_NAME_MATCH_TYPE = "match_type";
  @SerializedName(SERIALIZED_NAME_MATCH_TYPE)
  @javax.annotation.Nonnull
  private String matchType;

  public GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner() {
  }

  public GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner fromFloor(@javax.annotation.Nonnull String fromFloor) {
    this.fromFloor = fromFloor;
    return this;
  }

  /**
   * Get fromFloor
   * @return fromFloor
   */
  @javax.annotation.Nonnull
  public String getFromFloor() {
    return fromFloor;
  }

  public void setFromFloor(@javax.annotation.Nonnull String fromFloor) {
    this.fromFloor = fromFloor;
  }


  public GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner content(@javax.annotation.Nonnull String content) {
    this.content = content;
    return this;
  }

  /**
   * Get content
   * @return content
   */
  @javax.annotation.Nonnull
  public String getContent() {
    return content;
  }

  public void setContent(@javax.annotation.Nonnull String content) {
    this.content = content;
  }


  public GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner author(@javax.annotation.Nonnull String author) {
    this.author = author;
    return this;
  }

  /**
   * Get author
   * @return author
   */
  @javax.annotation.Nonnull
  public String getAuthor() {
    return author;
  }

  public void setAuthor(@javax.annotation.Nonnull String author) {
    this.author = author;
  }


  public GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner blockType(@javax.annotation.Nonnull Integer blockType) {
    this.blockType = blockType;
    return this;
  }

  /**
   * Get blockType
   * @return blockType
   */
  @javax.annotation.Nonnull
  public Integer getBlockType() {
    return blockType;
  }

  public void setBlockType(@javax.annotation.Nonnull Integer blockType) {
    this.blockType = blockType;
  }


  public GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner pid(@javax.annotation.Nonnull String pid) {
    this.pid = pid;
    return this;
  }

  /**
   * Get pid
   * @return pid
   */
  @javax.annotation.Nonnull
  public String getPid() {
    return pid;
  }

  public void setPid(@javax.annotation.Nonnull String pid) {
    this.pid = pid;
  }


  public GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner bid(@javax.annotation.Nonnull String bid) {
    this.bid = bid;
    return this;
  }

  /**
   * Get bid
   * @return bid
   */
  @javax.annotation.Nonnull
  public String getBid() {
    return bid;
  }

  public void setBid(@javax.annotation.Nonnull String bid) {
    this.bid = bid;
  }


  public GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner fid(@javax.annotation.Nonnull String fid) {
    this.fid = fid;
    return this;
  }

  /**
   * Get fid
   * @return fid
   */
  @javax.annotation.Nonnull
  public String getFid() {
    return fid;
  }

  public void setFid(@javax.annotation.Nonnull String fid) {
    this.fid = fid;
  }


  public GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner score(@javax.annotation.Nonnull BigDecimal score) {
    this.score = score;
    return this;
  }

  /**
   * Get score
   * @return score
   */
  @javax.annotation.Nonnull
  public BigDecimal getScore() {
    return score;
  }

  public void setScore(@javax.annotation.Nonnull BigDecimal score) {
    this.score = score;
  }


  public GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner matchType(@javax.annotation.Nonnull String matchType) {
    this.matchType = matchType;
    return this;
  }

  /**
   * Get matchType
   * @return matchType
   */
  @javax.annotation.Nonnull
  public String getMatchType() {
    return matchType;
  }

  public void setMatchType(@javax.annotation.Nonnull String matchType) {
    this.matchType = matchType;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner getConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner = (GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner) o;
    return Objects.equals(this.fromFloor, getConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner.fromFloor) &&
        Objects.equals(this.content, getConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner.content) &&
        Objects.equals(this.author, getConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner.author) &&
        Objects.equals(this.blockType, getConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner.blockType) &&
        Objects.equals(this.pid, getConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner.pid) &&
        Objects.equals(this.bid, getConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner.bid) &&
        Objects.equals(this.fid, getConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner.fid) &&
        Objects.equals(this.score, getConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner.score) &&
        Objects.equals(this.matchType, getConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner.matchType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fromFloor, content, author, blockType, pid, bid, fid, score, matchType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner {\n");
    sb.append("    fromFloor: ").append(toIndentedString(fromFloor)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    blockType: ").append(toIndentedString(blockType)).append("\n");
    sb.append("    pid: ").append(toIndentedString(pid)).append("\n");
    sb.append("    bid: ").append(toIndentedString(bid)).append("\n");
    sb.append("    fid: ").append(toIndentedString(fid)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    matchType: ").append(toIndentedString(matchType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("from_floor", "content", "author", "block_type", "pid", "bid", "fid", "score", "match_type"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("from_floor", "content", "author", "block_type", "pid", "bid", "fid", "score", "match_type"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner is not found in the empty JSON string", GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("from_floor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `from_floor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("from_floor").toString()));
      }
      if (!jsonObj.get("content").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `content` to be a primitive type in the JSON string but got `%s`", jsonObj.get("content").toString()));
      }
      if (!jsonObj.get("author").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `author` to be a primitive type in the JSON string but got `%s`", jsonObj.get("author").toString()));
      }
      if (!jsonObj.get("pid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `pid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pid").toString()));
      }
      if (!jsonObj.get("bid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `bid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bid").toString()));
      }
      if (!jsonObj.get("fid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `fid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fid").toString()));
      }
      if (!jsonObj.get("match_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `match_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("match_type").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner>() {
           @Override
           public void write(JsonWriter out, GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner
   * @throws IOException if the JSON string is invalid with respect to GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner
   */
  public static GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner.class);
  }

  /**
   * Convert an instance of GetConversations200ResponseConversationInnerAssistantFetchMultiplePostsResultsInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

