/*
 * Floor Memory
 * The set APIs are used to develop Floor pds which can be used as their personal assistants. This set of APIs are divided into two parts.
 * - Memory and
 * - Registration. The developer has two ways of using the APIs for the app development. Developer can choose to the Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ipomo.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.xfloor.memory.model;

import java.util.Objects;
import ai.xfloor.memory.model.GetConversations200ResponseConversationInnerAssistant;
import ai.xfloor.memory.model.GetConversations200ResponseConversationInnerUser;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.xfloor.memory.client.JSON;

/**
 * GetConversations200ResponseConversationInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class GetConversations200ResponseConversationInner {
  public static final String SERIALIZED_NAME_USER = "user";
  @SerializedName(SERIALIZED_NAME_USER)
  @javax.annotation.Nullable
  private GetConversations200ResponseConversationInnerUser user;

  public static final String SERIALIZED_NAME_ASSISTANT = "assistant";
  @SerializedName(SERIALIZED_NAME_ASSISTANT)
  @javax.annotation.Nullable
  private GetConversations200ResponseConversationInnerAssistant assistant;

  public GetConversations200ResponseConversationInner() {
  }

  public GetConversations200ResponseConversationInner user(@javax.annotation.Nullable GetConversations200ResponseConversationInnerUser user) {
    this.user = user;
    return this;
  }

  /**
   * Get user
   * @return user
   */
  @javax.annotation.Nullable
  public GetConversations200ResponseConversationInnerUser getUser() {
    return user;
  }

  public void setUser(@javax.annotation.Nullable GetConversations200ResponseConversationInnerUser user) {
    this.user = user;
  }


  public GetConversations200ResponseConversationInner assistant(@javax.annotation.Nullable GetConversations200ResponseConversationInnerAssistant assistant) {
    this.assistant = assistant;
    return this;
  }

  /**
   * Get assistant
   * @return assistant
   */
  @javax.annotation.Nullable
  public GetConversations200ResponseConversationInnerAssistant getAssistant() {
    return assistant;
  }

  public void setAssistant(@javax.annotation.Nullable GetConversations200ResponseConversationInnerAssistant assistant) {
    this.assistant = assistant;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetConversations200ResponseConversationInner getConversations200ResponseConversationInner = (GetConversations200ResponseConversationInner) o;
    return Objects.equals(this.user, getConversations200ResponseConversationInner.user) &&
        Objects.equals(this.assistant, getConversations200ResponseConversationInner.assistant);
  }

  @Override
  public int hashCode() {
    return Objects.hash(user, assistant);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetConversations200ResponseConversationInner {\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    assistant: ").append(toIndentedString(assistant)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("user", "assistant"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetConversations200ResponseConversationInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetConversations200ResponseConversationInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in GetConversations200ResponseConversationInner is not found in the empty JSON string", GetConversations200ResponseConversationInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetConversations200ResponseConversationInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetConversations200ResponseConversationInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `user`
      if (jsonObj.get("user") != null && !jsonObj.get("user").isJsonNull()) {
        GetConversations200ResponseConversationInnerUser.validateJsonElement(jsonObj.get("user"));
      }
      // validate the optional field `assistant`
      if (jsonObj.get("assistant") != null && !jsonObj.get("assistant").isJsonNull()) {
        GetConversations200ResponseConversationInnerAssistant.validateJsonElement(jsonObj.get("assistant"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetConversations200ResponseConversationInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetConversations200ResponseConversationInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetConversations200ResponseConversationInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetConversations200ResponseConversationInner.class));

       return (TypeAdapter<T>) new TypeAdapter<GetConversations200ResponseConversationInner>() {
           @Override
           public void write(JsonWriter out, GetConversations200ResponseConversationInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetConversations200ResponseConversationInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetConversations200ResponseConversationInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetConversations200ResponseConversationInner
   * @throws IOException if the JSON string is invalid with respect to GetConversations200ResponseConversationInner
   */
  public static GetConversations200ResponseConversationInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetConversations200ResponseConversationInner.class);
  }

  /**
   * Convert an instance of GetConversations200ResponseConversationInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

