/*
 * Floor Memory
 * The set APIs are used to develop Floor pds which can be used as their personal assistants. This set of APIs are divided into two parts.
 * - Memory and
 * - Registration. The developer has two ways of using the APIs for the app development. Developer can choose to the Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ipomo.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.xfloor.memory.model;

import java.util.Objects;
import ai.xfloor.memory.model.Media;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.xfloor.memory.client.JSON;

/**
 * Author details
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class GetRecentEvents200ResponseItemsInnerAuthor {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_FLOOR_ID = "floor_id";
  @SerializedName(SERIALIZED_NAME_FLOOR_ID)
  @javax.annotation.Nullable
  private String floorId;

  public static final String SERIALIZED_NAME_AVATAR = "avatar";
  @SerializedName(SERIALIZED_NAME_AVATAR)
  @javax.annotation.Nullable
  private Media avatar;

  public static final String SERIALIZED_NAME_FLOOR_UID = "floor_uid";
  @SerializedName(SERIALIZED_NAME_FLOOR_UID)
  @javax.annotation.Nullable
  private String floorUid;

  public GetRecentEvents200ResponseItemsInnerAuthor() {
  }

  public GetRecentEvents200ResponseItemsInnerAuthor name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Name of the author
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public GetRecentEvents200ResponseItemsInnerAuthor floorId(@javax.annotation.Nullable String floorId) {
    this.floorId = floorId;
    return this;
  }

  /**
   * Profile floor of the auther
   * @return floorId
   */
  @javax.annotation.Nullable
  public String getFloorId() {
    return floorId;
  }

  public void setFloorId(@javax.annotation.Nullable String floorId) {
    this.floorId = floorId;
  }


  public GetRecentEvents200ResponseItemsInnerAuthor avatar(@javax.annotation.Nullable Media avatar) {
    this.avatar = avatar;
    return this;
  }

  /**
   * Get avatar
   * @return avatar
   */
  @javax.annotation.Nullable
  public Media getAvatar() {
    return avatar;
  }

  public void setAvatar(@javax.annotation.Nullable Media avatar) {
    this.avatar = avatar;
  }


  public GetRecentEvents200ResponseItemsInnerAuthor floorUid(@javax.annotation.Nullable String floorUid) {
    this.floorUid = floorUid;
    return this;
  }

  /**
   * Unique 13 digit id of the profile floor
   * @return floorUid
   */
  @javax.annotation.Nullable
  public String getFloorUid() {
    return floorUid;
  }

  public void setFloorUid(@javax.annotation.Nullable String floorUid) {
    this.floorUid = floorUid;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetRecentEvents200ResponseItemsInnerAuthor getRecentEvents200ResponseItemsInnerAuthor = (GetRecentEvents200ResponseItemsInnerAuthor) o;
    return Objects.equals(this.name, getRecentEvents200ResponseItemsInnerAuthor.name) &&
        Objects.equals(this.floorId, getRecentEvents200ResponseItemsInnerAuthor.floorId) &&
        Objects.equals(this.avatar, getRecentEvents200ResponseItemsInnerAuthor.avatar) &&
        Objects.equals(this.floorUid, getRecentEvents200ResponseItemsInnerAuthor.floorUid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, floorId, avatar, floorUid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetRecentEvents200ResponseItemsInnerAuthor {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    floorId: ").append(toIndentedString(floorId)).append("\n");
    sb.append("    avatar: ").append(toIndentedString(avatar)).append("\n");
    sb.append("    floorUid: ").append(toIndentedString(floorUid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("name", "floor_id", "avatar", "floor_uid"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetRecentEvents200ResponseItemsInnerAuthor
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetRecentEvents200ResponseItemsInnerAuthor.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in GetRecentEvents200ResponseItemsInnerAuthor is not found in the empty JSON string", GetRecentEvents200ResponseItemsInnerAuthor.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetRecentEvents200ResponseItemsInnerAuthor.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetRecentEvents200ResponseItemsInnerAuthor` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("floor_id") != null && !jsonObj.get("floor_id").isJsonNull()) && !jsonObj.get("floor_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `floor_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("floor_id").toString()));
      }
      // validate the optional field `avatar`
      if (jsonObj.get("avatar") != null && !jsonObj.get("avatar").isJsonNull()) {
        Media.validateJsonElement(jsonObj.get("avatar"));
      }
      if ((jsonObj.get("floor_uid") != null && !jsonObj.get("floor_uid").isJsonNull()) && !jsonObj.get("floor_uid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `floor_uid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("floor_uid").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetRecentEvents200ResponseItemsInnerAuthor.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetRecentEvents200ResponseItemsInnerAuthor' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetRecentEvents200ResponseItemsInnerAuthor> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetRecentEvents200ResponseItemsInnerAuthor.class));

       return (TypeAdapter<T>) new TypeAdapter<GetRecentEvents200ResponseItemsInnerAuthor>() {
           @Override
           public void write(JsonWriter out, GetRecentEvents200ResponseItemsInnerAuthor value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetRecentEvents200ResponseItemsInnerAuthor read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetRecentEvents200ResponseItemsInnerAuthor given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetRecentEvents200ResponseItemsInnerAuthor
   * @throws IOException if the JSON string is invalid with respect to GetRecentEvents200ResponseItemsInnerAuthor
   */
  public static GetRecentEvents200ResponseItemsInnerAuthor fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetRecentEvents200ResponseItemsInnerAuthor.class);
  }

  /**
   * Convert an instance of GetRecentEvents200ResponseItemsInnerAuthor to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

