/*
 * Floor Memory
 * The set APIs are used to develop Floor pds which can be used as their personal assistants. This set of APIs are divided into two parts.
 * - Memory and
 * - Registration. The developer has two ways of using the APIs for the app development. Developer can choose to the Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ipomo.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.xfloor.memory.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.xfloor.memory.client.JSON;

/**
 * JSON format filters
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class QueryRequestFilters {
  public static final String SERIALIZED_NAME_TIME_FROM = "time_from";
  @SerializedName(SERIALIZED_NAME_TIME_FROM)
  @javax.annotation.Nonnull
  private String timeFrom;

  public static final String SERIALIZED_NAME_TIME_TO = "time_to";
  @SerializedName(SERIALIZED_NAME_TIME_TO)
  @javax.annotation.Nonnull
  private String timeTo;

  public static final String SERIALIZED_NAME_FILTER_TYPES = "filter_types";
  @SerializedName(SERIALIZED_NAME_FILTER_TYPES)
  @javax.annotation.Nonnull
  private String filterTypes;

  public static final String SERIALIZED_NAME_FILTER_TAGS = "filter_tags";
  @SerializedName(SERIALIZED_NAME_FILTER_TAGS)
  @javax.annotation.Nonnull
  private String filterTags;

  public QueryRequestFilters() {
  }

  public QueryRequestFilters timeFrom(@javax.annotation.Nonnull String timeFrom) {
    this.timeFrom = timeFrom;
    return this;
  }

  /**
   * Start timestamp for filtering content by creation or update time.
   * @return timeFrom
   */
  @javax.annotation.Nonnull
  public String getTimeFrom() {
    return timeFrom;
  }

  public void setTimeFrom(@javax.annotation.Nonnull String timeFrom) {
    this.timeFrom = timeFrom;
  }


  public QueryRequestFilters timeTo(@javax.annotation.Nonnull String timeTo) {
    this.timeTo = timeTo;
    return this;
  }

  /**
   * End timestamp for filtering content by creation or update time.
   * @return timeTo
   */
  @javax.annotation.Nonnull
  public String getTimeTo() {
    return timeTo;
  }

  public void setTimeTo(@javax.annotation.Nonnull String timeTo) {
    this.timeTo = timeTo;
  }


  public QueryRequestFilters filterTypes(@javax.annotation.Nonnull String filterTypes) {
    this.filterTypes = filterTypes;
    return this;
  }

  /**
   * Content types to include (e.g., post, forum).
   * @return filterTypes
   */
  @javax.annotation.Nonnull
  public String getFilterTypes() {
    return filterTypes;
  }

  public void setFilterTypes(@javax.annotation.Nonnull String filterTypes) {
    this.filterTypes = filterTypes;
  }


  public QueryRequestFilters filterTags(@javax.annotation.Nonnull String filterTags) {
    this.filterTags = filterTags;
    return this;
  }

  /**
   * Tags used to further refine the query results.
   * @return filterTags
   */
  @javax.annotation.Nonnull
  public String getFilterTags() {
    return filterTags;
  }

  public void setFilterTags(@javax.annotation.Nonnull String filterTags) {
    this.filterTags = filterTags;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryRequestFilters queryRequestFilters = (QueryRequestFilters) o;
    return Objects.equals(this.timeFrom, queryRequestFilters.timeFrom) &&
        Objects.equals(this.timeTo, queryRequestFilters.timeTo) &&
        Objects.equals(this.filterTypes, queryRequestFilters.filterTypes) &&
        Objects.equals(this.filterTags, queryRequestFilters.filterTags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeFrom, timeTo, filterTypes, filterTags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryRequestFilters {\n");
    sb.append("    timeFrom: ").append(toIndentedString(timeFrom)).append("\n");
    sb.append("    timeTo: ").append(toIndentedString(timeTo)).append("\n");
    sb.append("    filterTypes: ").append(toIndentedString(filterTypes)).append("\n");
    sb.append("    filterTags: ").append(toIndentedString(filterTags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("time_from", "time_to", "filter_types", "filter_tags"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("time_from", "time_to", "filter_types", "filter_tags"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to QueryRequestFilters
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!QueryRequestFilters.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in QueryRequestFilters is not found in the empty JSON string", QueryRequestFilters.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!QueryRequestFilters.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `QueryRequestFilters` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : QueryRequestFilters.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("time_from").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `time_from` to be a primitive type in the JSON string but got `%s`", jsonObj.get("time_from").toString()));
      }
      if (!jsonObj.get("time_to").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `time_to` to be a primitive type in the JSON string but got `%s`", jsonObj.get("time_to").toString()));
      }
      if (!jsonObj.get("filter_types").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `filter_types` to be a primitive type in the JSON string but got `%s`", jsonObj.get("filter_types").toString()));
      }
      if (!jsonObj.get("filter_tags").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `filter_tags` to be a primitive type in the JSON string but got `%s`", jsonObj.get("filter_tags").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!QueryRequestFilters.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'QueryRequestFilters' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<QueryRequestFilters> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(QueryRequestFilters.class));

       return (TypeAdapter<T>) new TypeAdapter<QueryRequestFilters>() {
           @Override
           public void write(JsonWriter out, QueryRequestFilters value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public QueryRequestFilters read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of QueryRequestFilters given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of QueryRequestFilters
   * @throws IOException if the JSON string is invalid with respect to QueryRequestFilters
   */
  public static QueryRequestFilters fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, QueryRequestFilters.class);
  }

  /**
   * Convert an instance of QueryRequestFilters to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

