/*
 * Floor Memory
 * The set APIs are used to develop Floor pds which can be used as their personal assistants.   This set of APIs are divided into two parts.  - Memory and  - Registration.   The developer has two ways of using the APIs for the app development. Developer can choose to the  Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ipomo.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.xfloor.memory.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.xfloor.memory.client.JSON;

/**
 * SendValidationCodeRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class SendValidationCodeRequest {
  public static final String SERIALIZED_NAME_USER_ID = "user_id";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  @javax.annotation.Nullable
  private String userId;

  public static final String SERIALIZED_NAME_MODE = "mode";
  @SerializedName(SERIALIZED_NAME_MODE)
  @javax.annotation.Nonnull
  private String mode;

  public static final String SERIALIZED_NAME_MOBILES_NUMBER = "mobiles_number";
  @SerializedName(SERIALIZED_NAME_MOBILES_NUMBER)
  @javax.annotation.Nullable
  private String mobilesNumber;

  public static final String SERIALIZED_NAME_EMAIL_ID = "email_id";
  @SerializedName(SERIALIZED_NAME_EMAIL_ID)
  @javax.annotation.Nullable
  private String emailId;

  public SendValidationCodeRequest() {
  }

  public SendValidationCodeRequest userId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
    return this;
  }

  /**
   * user id
   * @return userId
   */
  @javax.annotation.Nullable
  public String getUserId() {
    return userId;
  }

  public void setUserId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
  }


  public SendValidationCodeRequest mode(@javax.annotation.Nonnull String mode) {
    this.mode = mode;
    return this;
  }

  /**
   * Mode - 0 for getting activation code to change email or mobile number, 1 for password change
   * @return mode
   */
  @javax.annotation.Nonnull
  public String getMode() {
    return mode;
  }

  public void setMode(@javax.annotation.Nonnull String mode) {
    this.mode = mode;
  }


  public SendValidationCodeRequest mobilesNumber(@javax.annotation.Nullable String mobilesNumber) {
    this.mobilesNumber = mobilesNumber;
    return this;
  }

  /**
   * Get mobilesNumber
   * @return mobilesNumber
   */
  @javax.annotation.Nullable
  public String getMobilesNumber() {
    return mobilesNumber;
  }

  public void setMobilesNumber(@javax.annotation.Nullable String mobilesNumber) {
    this.mobilesNumber = mobilesNumber;
  }


  public SendValidationCodeRequest emailId(@javax.annotation.Nullable String emailId) {
    this.emailId = emailId;
    return this;
  }

  /**
   * Get emailId
   * @return emailId
   */
  @javax.annotation.Nullable
  public String getEmailId() {
    return emailId;
  }

  public void setEmailId(@javax.annotation.Nullable String emailId) {
    this.emailId = emailId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendValidationCodeRequest sendValidationCodeRequest = (SendValidationCodeRequest) o;
    return Objects.equals(this.userId, sendValidationCodeRequest.userId) &&
        Objects.equals(this.mode, sendValidationCodeRequest.mode) &&
        Objects.equals(this.mobilesNumber, sendValidationCodeRequest.mobilesNumber) &&
        Objects.equals(this.emailId, sendValidationCodeRequest.emailId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, mode, mobilesNumber, emailId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendValidationCodeRequest {\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    mobilesNumber: ").append(toIndentedString(mobilesNumber)).append("\n");
    sb.append("    emailId: ").append(toIndentedString(emailId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("user_id", "mode", "mobiles_number", "email_id"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("mode"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SendValidationCodeRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SendValidationCodeRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in SendValidationCodeRequest is not found in the empty JSON string", SendValidationCodeRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SendValidationCodeRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `SendValidationCodeRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SendValidationCodeRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("user_id") != null && !jsonObj.get("user_id").isJsonNull()) && !jsonObj.get("user_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `user_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("user_id").toString()));
      }
      if (!jsonObj.get("mode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `mode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mode").toString()));
      }
      if ((jsonObj.get("mobiles_number") != null && !jsonObj.get("mobiles_number").isJsonNull()) && !jsonObj.get("mobiles_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `mobiles_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mobiles_number").toString()));
      }
      if ((jsonObj.get("email_id") != null && !jsonObj.get("email_id").isJsonNull()) && !jsonObj.get("email_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `email_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SendValidationCodeRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SendValidationCodeRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SendValidationCodeRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SendValidationCodeRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<SendValidationCodeRequest>() {
           @Override
           public void write(JsonWriter out, SendValidationCodeRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SendValidationCodeRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SendValidationCodeRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SendValidationCodeRequest
   * @throws IOException if the JSON string is invalid with respect to SendValidationCodeRequest
   */
  public static SendValidationCodeRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SendValidationCodeRequest.class);
  }

  /**
   * Convert an instance of SendValidationCodeRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

