/**
 * Floor Memory
 * The set APIs are used to develop Floor pds which can be used as their personal assistants.   This set of APIs are divided into two parts.  - Memory and  - Registration.   The developer has two ways of using the APIs for the app development. Developer can choose to the  Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ipomo.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.XfloorFloorMemorySdkJs);
  }
}(this, function(expect, XfloorFloorMemorySdkJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new XfloorFloorMemorySdkJs.QueryResponseItemsInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('QueryResponseItemsInner', function() {
    it('should create an instance of QueryResponseItemsInner', function() {
      // uncomment below and update the code to test QueryResponseItemsInner
      //var instance = new XfloorFloorMemorySdkJs.QueryResponseItemsInner();
      //expect(instance).to.be.a(XfloorFloorMemorySdkJs.QueryResponseItemsInner);
    });

    it('should have the property blockType (base name: "block_type")', function() {
      // uncomment below and update the code to test the property blockType
      //var instance = new XfloorFloorMemorySdkJs.QueryResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property blockId (base name: "block_id")', function() {
      // uncomment below and update the code to test the property blockId
      //var instance = new XfloorFloorMemorySdkJs.QueryResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property floorUid (base name: "floor_uid")', function() {
      // uncomment below and update the code to test the property floorUid
      //var instance = new XfloorFloorMemorySdkJs.QueryResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property eventId (base name: "event_id")', function() {
      // uncomment below and update the code to test the property eventId
      //var instance = new XfloorFloorMemorySdkJs.QueryResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property text (base name: "text")', function() {
      // uncomment below and update the code to test the property text
      //var instance = new XfloorFloorMemorySdkJs.QueryResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property score (base name: "score")', function() {
      // uncomment below and update the code to test the property score
      //var instance = new XfloorFloorMemorySdkJs.QueryResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property blockTitle (base name: "block_title")', function() {
      // uncomment below and update the code to test the property blockTitle
      //var instance = new XfloorFloorMemorySdkJs.QueryResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property blockDetails (base name: "block_details")', function() {
      // uncomment below and update the code to test the property blockDetails
      //var instance = new XfloorFloorMemorySdkJs.QueryResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property fromFloorUid (base name: "from_floor_uid")', function() {
      // uncomment below and update the code to test the property fromFloorUid
      //var instance = new XfloorFloorMemorySdkJs.QueryResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property userId (base name: "user_id")', function() {
      // uncomment below and update the code to test the property userId
      //var instance = new XfloorFloorMemorySdkJs.QueryResponseItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property matchType (base name: "match_type")', function() {
      // uncomment below and update the code to test the property matchType
      //var instance = new XfloorFloorMemorySdkJs.QueryResponseItemsInner();
      //expect(instance).to.be();
    });

  });

}));
