/* tslint:disable */
/* eslint-disable */
/**
 * Floor Memory
 * The set APIs are used to develop Floor pds which can be used as their personal assistants. This set of APIs are divided into two parts.
 * - Memory and
 * - Registration. The developer has two ways of using the APIs for the app development. Developer can choose to the Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ipomo.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Profile Pick details
 * @export
 * @interface ChangeEmail200ResponseProfileAvatar
 */
export interface ChangeEmail200ResponseProfileAvatar {
    /**
     * Image URL
     * @type {string}
     * @memberof ChangeEmail200ResponseProfileAvatar
     */
    url: string;
    /**
     * Image ID
     * @type {string}
     * @memberof ChangeEmail200ResponseProfileAvatar
     */
    id: string;
}

/**
 * Check if a given object implements the ChangeEmail200ResponseProfileAvatar interface.
 */
export function instanceOfChangeEmail200ResponseProfileAvatar(value: object): value is ChangeEmail200ResponseProfileAvatar {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ChangeEmail200ResponseProfileAvatarFromJSON(json: any): ChangeEmail200ResponseProfileAvatar {
    return ChangeEmail200ResponseProfileAvatarFromJSONTyped(json, false);
}

export function ChangeEmail200ResponseProfileAvatarFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeEmail200ResponseProfileAvatar {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'id': json['id'],
    };
}

export function ChangeEmail200ResponseProfileAvatarToJSON(json: any): ChangeEmail200ResponseProfileAvatar {
    return ChangeEmail200ResponseProfileAvatarToJSONTyped(json, false);
}

export function ChangeEmail200ResponseProfileAvatarToJSONTyped(value?: ChangeEmail200ResponseProfileAvatar | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'id': value['id'],
    };
}

