/* tslint:disable */
/* eslint-disable */
/**
 * Floor Memory
 * The set APIs are used to develop Floor pds which can be used as their personal assistants. This set of APIs are divided into two parts.
 * - Memory and
 * - Registration. The developer has two ways of using the APIs for the app development. Developer can choose to the Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ipomo.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlockDetails } from './BlockDetails';
import {
    BlockDetailsFromJSON,
    BlockDetailsFromJSONTyped,
    BlockDetailsToJSON,
    BlockDetailsToJSONTyped,
} from './BlockDetails';
import type { Media } from './Media';
import {
    MediaFromJSON,
    MediaFromJSONTyped,
    MediaToJSON,
    MediaToJSONTyped,
} from './Media';

/**
 * 
 * @export
 * @interface ChangeEmail200ResponsePodInfo
 */
export interface ChangeEmail200ResponsePodInfo {
    /**
     * 
     * @type {string}
     * @memberof ChangeEmail200ResponsePodInfo
     */
    floorId: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeEmail200ResponsePodInfo
     */
    isOwner?: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeEmail200ResponsePodInfo
     */
    appId?: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeEmail200ResponsePodInfo
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeEmail200ResponsePodInfo
     */
    details?: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeEmail200ResponsePodInfo
     */
    floorUid: string;
    /**
     * 
     * @type {Array<BlockDetails>}
     * @memberof ChangeEmail200ResponsePodInfo
     */
    blocks: Array<BlockDetails>;
    /**
     * 
     * @type {Media}
     * @memberof ChangeEmail200ResponsePodInfo
     */
    avatar?: Media;
}

/**
 * Check if a given object implements the ChangeEmail200ResponsePodInfo interface.
 */
export function instanceOfChangeEmail200ResponsePodInfo(value: object): value is ChangeEmail200ResponsePodInfo {
    if (!('floorId' in value) || value['floorId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('floorUid' in value) || value['floorUid'] === undefined) return false;
    if (!('blocks' in value) || value['blocks'] === undefined) return false;
    return true;
}

export function ChangeEmail200ResponsePodInfoFromJSON(json: any): ChangeEmail200ResponsePodInfo {
    return ChangeEmail200ResponsePodInfoFromJSONTyped(json, false);
}

export function ChangeEmail200ResponsePodInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeEmail200ResponsePodInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'floorId': json['floor_id'],
        'isOwner': json['is_owner'] == null ? undefined : json['is_owner'],
        'appId': json['app_id'] == null ? undefined : json['app_id'],
        'title': json['title'],
        'details': json['details'] == null ? undefined : json['details'],
        'floorUid': json['floor_uid'],
        'blocks': ((json['blocks'] as Array<any>).map(BlockDetailsFromJSON)),
        'avatar': json['avatar'] == null ? undefined : MediaFromJSON(json['avatar']),
    };
}

export function ChangeEmail200ResponsePodInfoToJSON(json: any): ChangeEmail200ResponsePodInfo {
    return ChangeEmail200ResponsePodInfoToJSONTyped(json, false);
}

export function ChangeEmail200ResponsePodInfoToJSONTyped(value?: ChangeEmail200ResponsePodInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'floor_id': value['floorId'],
        'is_owner': value['isOwner'],
        'app_id': value['appId'],
        'title': value['title'],
        'details': value['details'],
        'floor_uid': value['floorUid'],
        'blocks': ((value['blocks'] as Array<any>).map(BlockDetailsToJSON)),
        'avatar': MediaToJSON(value['avatar']),
    };
}

