/* tslint:disable */
/* eslint-disable */
/**
 * Floor Memory
 * The set APIs are used to develop Floor pds which can be used as their personal assistants. This set of APIs are divided into two parts.
 * - Memory and
 * - Registration. The developer has two ways of using the APIs for the app development. Developer can choose to the Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ipomo.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetConversations200ResponseConversationInnerAssistantChoicesInnerPromptDetails } from './GetConversations200ResponseConversationInnerAssistantChoicesInnerPromptDetails';
import {
    GetConversations200ResponseConversationInnerAssistantChoicesInnerPromptDetailsFromJSON,
    GetConversations200ResponseConversationInnerAssistantChoicesInnerPromptDetailsFromJSONTyped,
    GetConversations200ResponseConversationInnerAssistantChoicesInnerPromptDetailsToJSON,
    GetConversations200ResponseConversationInnerAssistantChoicesInnerPromptDetailsToJSONTyped,
} from './GetConversations200ResponseConversationInnerAssistantChoicesInnerPromptDetails';
import type { GetConversations200ResponseConversationInnerAssistantChoicesInnerMessage } from './GetConversations200ResponseConversationInnerAssistantChoicesInnerMessage';
import {
    GetConversations200ResponseConversationInnerAssistantChoicesInnerMessageFromJSON,
    GetConversations200ResponseConversationInnerAssistantChoicesInnerMessageFromJSONTyped,
    GetConversations200ResponseConversationInnerAssistantChoicesInnerMessageToJSON,
    GetConversations200ResponseConversationInnerAssistantChoicesInnerMessageToJSONTyped,
} from './GetConversations200ResponseConversationInnerAssistantChoicesInnerMessage';
import type { GetConversations200ResponseConversationInnerAssistantChoicesInnerAiModelDetails } from './GetConversations200ResponseConversationInnerAssistantChoicesInnerAiModelDetails';
import {
    GetConversations200ResponseConversationInnerAssistantChoicesInnerAiModelDetailsFromJSON,
    GetConversations200ResponseConversationInnerAssistantChoicesInnerAiModelDetailsFromJSONTyped,
    GetConversations200ResponseConversationInnerAssistantChoicesInnerAiModelDetailsToJSON,
    GetConversations200ResponseConversationInnerAssistantChoicesInnerAiModelDetailsToJSONTyped,
} from './GetConversations200ResponseConversationInnerAssistantChoicesInnerAiModelDetails';

/**
 * 
 * @export
 * @interface GetConversations200ResponseConversationInnerAssistantChoicesInner
 */
export interface GetConversations200ResponseConversationInnerAssistantChoicesInner {
    /**
     * 
     * @type {number}
     * @memberof GetConversations200ResponseConversationInnerAssistantChoicesInner
     */
    index?: number;
    /**
     * 
     * @type {GetConversations200ResponseConversationInnerAssistantChoicesInnerMessage}
     * @memberof GetConversations200ResponseConversationInnerAssistantChoicesInner
     */
    message?: GetConversations200ResponseConversationInnerAssistantChoicesInnerMessage;
    /**
     * 
     * @type {string}
     * @memberof GetConversations200ResponseConversationInnerAssistantChoicesInner
     */
    finishReason?: string;
    /**
     * 
     * @type {GetConversations200ResponseConversationInnerAssistantChoicesInnerAiModelDetails}
     * @memberof GetConversations200ResponseConversationInnerAssistantChoicesInner
     */
    aiModelDetails?: GetConversations200ResponseConversationInnerAssistantChoicesInnerAiModelDetails;
    /**
     * 
     * @type {GetConversations200ResponseConversationInnerAssistantChoicesInnerPromptDetails}
     * @memberof GetConversations200ResponseConversationInnerAssistantChoicesInner
     */
    promptDetails?: GetConversations200ResponseConversationInnerAssistantChoicesInnerPromptDetails;
}

/**
 * Check if a given object implements the GetConversations200ResponseConversationInnerAssistantChoicesInner interface.
 */
export function instanceOfGetConversations200ResponseConversationInnerAssistantChoicesInner(value: object): value is GetConversations200ResponseConversationInnerAssistantChoicesInner {
    return true;
}

export function GetConversations200ResponseConversationInnerAssistantChoicesInnerFromJSON(json: any): GetConversations200ResponseConversationInnerAssistantChoicesInner {
    return GetConversations200ResponseConversationInnerAssistantChoicesInnerFromJSONTyped(json, false);
}

export function GetConversations200ResponseConversationInnerAssistantChoicesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetConversations200ResponseConversationInnerAssistantChoicesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'] == null ? undefined : json['index'],
        'message': json['message'] == null ? undefined : GetConversations200ResponseConversationInnerAssistantChoicesInnerMessageFromJSON(json['message']),
        'finishReason': json['finish_reason'] == null ? undefined : json['finish_reason'],
        'aiModelDetails': json['ai_model_details'] == null ? undefined : GetConversations200ResponseConversationInnerAssistantChoicesInnerAiModelDetailsFromJSON(json['ai_model_details']),
        'promptDetails': json['prompt_details'] == null ? undefined : GetConversations200ResponseConversationInnerAssistantChoicesInnerPromptDetailsFromJSON(json['prompt_details']),
    };
}

export function GetConversations200ResponseConversationInnerAssistantChoicesInnerToJSON(json: any): GetConversations200ResponseConversationInnerAssistantChoicesInner {
    return GetConversations200ResponseConversationInnerAssistantChoicesInnerToJSONTyped(json, false);
}

export function GetConversations200ResponseConversationInnerAssistantChoicesInnerToJSONTyped(value?: GetConversations200ResponseConversationInnerAssistantChoicesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index': value['index'],
        'message': GetConversations200ResponseConversationInnerAssistantChoicesInnerMessageToJSON(value['message']),
        'finish_reason': value['finishReason'],
        'ai_model_details': GetConversations200ResponseConversationInnerAssistantChoicesInnerAiModelDetailsToJSON(value['aiModelDetails']),
        'prompt_details': GetConversations200ResponseConversationInnerAssistantChoicesInnerPromptDetailsToJSON(value['promptDetails']),
    };
}

