/* tslint:disable */
/* eslint-disable */
/**
 * Floor Memory
 * The set APIs are used to develop Floor pds which can be used as their personal assistants. This set of APIs are divided into two parts.
 * - Memory and
 * - Registration. The developer has two ways of using the APIs for the app development. Developer can choose to the Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ipomo.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlockDetails } from './BlockDetails';
import {
    BlockDetailsFromJSON,
    BlockDetailsFromJSONTyped,
    BlockDetailsToJSON,
    BlockDetailsToJSONTyped,
} from './BlockDetails';
import type { Media } from './Media';
import {
    MediaFromJSON,
    MediaFromJSONTyped,
    MediaToJSON,
    MediaToJSONTyped,
} from './Media';

/**
 * 
 * @export
 * @interface GetFloorInformation200Response
 */
export interface GetFloorInformation200Response {
    /**
     * Pod floor ID
     * @type {string}
     * @memberof GetFloorInformation200Response
     */
    floorId: string;
    /**
     * Title
     * @type {string}
     * @memberof GetFloorInformation200Response
     */
    title: string;
    /**
     * Brief description about the Pod floor
     * @type {string}
     * @memberof GetFloorInformation200Response
     */
    details?: string;
    /**
     * Unique numeric ID of the pod floor
     * @type {string}
     * @memberof GetFloorInformation200Response
     */
    fid: string;
    /**
     * List of blocks
     * @type {Array<BlockDetails>}
     * @memberof GetFloorInformation200Response
     */
    blocks?: Array<BlockDetails>;
    /**
     * 
     * @type {Media}
     * @memberof GetFloorInformation200Response
     */
    avatar?: Media;
}

/**
 * Check if a given object implements the GetFloorInformation200Response interface.
 */
export function instanceOfGetFloorInformation200Response(value: object): value is GetFloorInformation200Response {
    if (!('floorId' in value) || value['floorId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('fid' in value) || value['fid'] === undefined) return false;
    return true;
}

export function GetFloorInformation200ResponseFromJSON(json: any): GetFloorInformation200Response {
    return GetFloorInformation200ResponseFromJSONTyped(json, false);
}

export function GetFloorInformation200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFloorInformation200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'floorId': json['floor_id'],
        'title': json['title'],
        'details': json['details'] == null ? undefined : json['details'],
        'fid': json['fid'],
        'blocks': json['blocks'] == null ? undefined : ((json['blocks'] as Array<any>).map(BlockDetailsFromJSON)),
        'avatar': json['avatar'] == null ? undefined : MediaFromJSON(json['avatar']),
    };
}

export function GetFloorInformation200ResponseToJSON(json: any): GetFloorInformation200Response {
    return GetFloorInformation200ResponseToJSONTyped(json, false);
}

export function GetFloorInformation200ResponseToJSONTyped(value?: GetFloorInformation200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'floor_id': value['floorId'],
        'title': value['title'],
        'details': value['details'],
        'fid': value['fid'],
        'blocks': value['blocks'] == null ? undefined : ((value['blocks'] as Array<any>).map(BlockDetailsToJSON)),
        'avatar': MediaToJSON(value['avatar']),
    };
}

