/* tslint:disable */
/* eslint-disable */
/**
 * Floor Memory
 * The set APIs are used to develop Floor pds which can be used as their personal assistants.   This set of APIs are divided into two parts.  - Memory and  - Registration.   The developer has two ways of using the APIs for the app development. Developer can choose to the  Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ipomo.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueryResponseItemsInner } from './QueryResponseItemsInner';
import {
    QueryResponseItemsInnerFromJSON,
    QueryResponseItemsInnerFromJSONTyped,
    QueryResponseItemsInnerToJSON,
    QueryResponseItemsInnerToJSONTyped,
} from './QueryResponseItemsInner';

/**
 * 
 * @export
 * @interface QueryResponse
 */
export interface QueryResponse {
    /**
     * List of source content
     * @type {Array<QueryResponseItemsInner>}
     * @memberof QueryResponse
     */
    items?: Array<QueryResponseItemsInner>;
    /**
     * Summary of the posts
     * @type {string}
     * @memberof QueryResponse
     */
    answer?: string;
}

/**
 * Check if a given object implements the QueryResponse interface.
 */
export function instanceOfQueryResponse(value: object): value is QueryResponse {
    return true;
}

export function QueryResponseFromJSON(json: any): QueryResponse {
    return QueryResponseFromJSONTyped(json, false);
}

export function QueryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(QueryResponseItemsInnerFromJSON)),
        'answer': json['answer'] == null ? undefined : json['answer'],
    };
}

export function QueryResponseToJSON(json: any): QueryResponse {
    return QueryResponseToJSONTyped(json, false);
}

export function QueryResponseToJSONTyped(value?: QueryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(QueryResponseItemsInnerToJSON)),
        'answer': value['answer'],
    };
}

