/* tslint:disable */
/* eslint-disable */
/**
 * Floor Memory
 * The set APIs are used to develop Floor pds which can be used as their personal assistants.   This set of APIs are divided into two parts.  - Memory and  - Registration.   The developer has two ways of using the APIs for the app development. Developer can choose to the  Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ipomo.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendValidationCode200Response
 */
export interface SendValidationCode200Response {
    /**
     * Validation code sent successfully
     * @type {string}
     * @memberof SendValidationCode200Response
     */
    success: string;
}

/**
 * Check if a given object implements the SendValidationCode200Response interface.
 */
export function instanceOfSendValidationCode200Response(value: object): value is SendValidationCode200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function SendValidationCode200ResponseFromJSON(json: any): SendValidationCode200Response {
    return SendValidationCode200ResponseFromJSONTyped(json, false);
}

export function SendValidationCode200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendValidationCode200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function SendValidationCode200ResponseToJSON(json: any): SendValidationCode200Response {
    return SendValidationCode200ResponseToJSONTyped(json, false);
}

export function SendValidationCode200ResponseToJSONTyped(value?: SendValidationCode200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

