/* tslint:disable */
/* eslint-disable */
/**
 * Floor Memory
 * The set APIs are used to develop Floor pds which can be used as their personal assistants. This set of APIs are divided into two parts.
 * - Memory and
 * - Registration. The developer has two ways of using the APIs for the app development. Developer can choose to the Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ipomo.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChangeEmail200ResponseProfile } from './ChangeEmail200ResponseProfile';
import {
    ChangeEmail200ResponseProfileFromJSON,
    ChangeEmail200ResponseProfileFromJSONTyped,
    ChangeEmail200ResponseProfileToJSON,
    ChangeEmail200ResponseProfileToJSONTyped,
} from './ChangeEmail200ResponseProfile';
import type { ChangeEmail200ResponsePodInfo } from './ChangeEmail200ResponsePodInfo';
import {
    ChangeEmail200ResponsePodInfoFromJSON,
    ChangeEmail200ResponsePodInfoFromJSONTyped,
    ChangeEmail200ResponsePodInfoToJSON,
    ChangeEmail200ResponsePodInfoToJSONTyped,
} from './ChangeEmail200ResponsePodInfo';

/**
 * 
 * @export
 * @interface UserDetails
 */
export interface UserDetails {
    /**
     * 
     * @type {ChangeEmail200ResponseProfile}
     * @memberof UserDetails
     */
    profile: ChangeEmail200ResponseProfile;
    /**
     * 
     * @type {ChangeEmail200ResponsePodInfo}
     * @memberof UserDetails
     */
    podInfo: ChangeEmail200ResponsePodInfo;
    /**
     * App ID
     * @type {string}
     * @memberof UserDetails
     */
    appId?: string;
}

/**
 * Check if a given object implements the UserDetails interface.
 */
export function instanceOfUserDetails(value: object): value is UserDetails {
    if (!('profile' in value) || value['profile'] === undefined) return false;
    if (!('podInfo' in value) || value['podInfo'] === undefined) return false;
    return true;
}

export function UserDetailsFromJSON(json: any): UserDetails {
    return UserDetailsFromJSONTyped(json, false);
}

export function UserDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'profile': ChangeEmail200ResponseProfileFromJSON(json['profile']),
        'podInfo': ChangeEmail200ResponsePodInfoFromJSON(json['pod_info']),
        'appId': json['app_id'] == null ? undefined : json['app_id'],
    };
}

export function UserDetailsToJSON(json: any): UserDetails {
    return UserDetailsToJSONTyped(json, false);
}

export function UserDetailsToJSONTyped(value?: UserDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'profile': ChangeEmail200ResponseProfileToJSON(value['profile']),
        'pod_info': ChangeEmail200ResponsePodInfoToJSON(value['podInfo']),
        'app_id': value['appId'],
    };
}

