/* tslint:disable */
/* eslint-disable */
/**
 * Floor Memory
 * The set APIs are used to develop Floor pds which can be used as their personal assistants.   This set of APIs are divided into two parts.  - Memory and  - Registration.   The developer has two ways of using the APIs for the app development. Developer can choose to the  Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ipomo.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidateCode412Response
 */
export interface ValidateCode412Response {
    /**
     * Something went wrong. Try again
     * @type {string}
     * @memberof ValidateCode412Response
     */
    error: string;
}

/**
 * Check if a given object implements the ValidateCode412Response interface.
 */
export function instanceOfValidateCode412Response(value: object): value is ValidateCode412Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ValidateCode412ResponseFromJSON(json: any): ValidateCode412Response {
    return ValidateCode412ResponseFromJSONTyped(json, false);
}

export function ValidateCode412ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidateCode412Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function ValidateCode412ResponseToJSON(json: any): ValidateCode412Response {
    return ValidateCode412ResponseToJSONTyped(json, false);
}

export function ValidateCode412ResponseToJSONTyped(value?: ValidateCode412Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

