/**
 * Floor Memory
 * The set APIs are used to develop Floor pds which can be used as their personal assistants. This set of APIs are divided into two parts.
 * - Memory and
 * - Registration. The developer has two ways of using the APIs for the app development. Developer can choose to the Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ipomo.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConversationThreads200ResponseThreadsInner from './ConversationThreads200ResponseThreadsInner';

/**
 * The ConversationThreads200Response model module.
 * @module model/ConversationThreads200Response
 * @version 1.0.7
 */
class ConversationThreads200Response {
    /**
     * Constructs a new <code>ConversationThreads200Response</code>.
     * @alias module:model/ConversationThreads200Response
     * @param userId {String} 
     * @param threads {Array.<module:model/ConversationThreads200ResponseThreadsInner>} 
     */
    constructor(userId, threads) { 
        
        ConversationThreads200Response.initialize(this, userId, threads);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userId, threads) { 
        obj['user_id'] = userId;
        obj['threads'] = threads;
    }

    /**
     * Constructs a <code>ConversationThreads200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConversationThreads200Response} obj Optional instance to populate.
     * @return {module:model/ConversationThreads200Response} The populated <code>ConversationThreads200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConversationThreads200Response();

            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
            if (data.hasOwnProperty('threads')) {
                obj['threads'] = ApiClient.convertToType(data['threads'], [ConversationThreads200ResponseThreadsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ConversationThreads200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ConversationThreads200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ConversationThreads200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['user_id'] && !(typeof data['user_id'] === 'string' || data['user_id'] instanceof String)) {
            throw new Error("Expected the field `user_id` to be a primitive type in the JSON string but got " + data['user_id']);
        }
        if (data['threads']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['threads'])) {
                throw new Error("Expected the field `threads` to be an array in the JSON data but got " + data['threads']);
            }
            // validate the optional field `threads` (array)
            for (const item of data['threads']) {
                ConversationThreads200ResponseThreadsInner.validateJSON(item);
            };
        }

        return true;
    }


}

ConversationThreads200Response.RequiredProperties = ["user_id", "threads"];

/**
 * @member {String} user_id
 */
ConversationThreads200Response.prototype['user_id'] = undefined;

/**
 * @member {Array.<module:model/ConversationThreads200ResponseThreadsInner>} threads
 */
ConversationThreads200Response.prototype['threads'] = undefined;






export default ConversationThreads200Response;

