/**
 * Floor Memory
 * The set APIs are used to develop Floor pds which can be used as their personal assistants. This set of APIs are divided into two parts.
 * - Memory and
 * - Registration. The developer has two ways of using the APIs for the app development. Developer can choose to the Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ipomo.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EditFloor400ResponseError from './EditFloor400ResponseError';

/**
 * The EditFloor400Response model module.
 * @module model/EditFloor400Response
 * @version 1.0.9
 */
class EditFloor400Response {
    /**
     * Constructs a new <code>EditFloor400Response</code>.
     * @alias module:model/EditFloor400Response
     * @param error {module:model/EditFloor400ResponseError} 
     */
    constructor(error) { 
        
        EditFloor400Response.initialize(this, error);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, error) { 
        obj['error'] = error;
    }

    /**
     * Constructs a <code>EditFloor400Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EditFloor400Response} obj Optional instance to populate.
     * @return {module:model/EditFloor400Response} The populated <code>EditFloor400Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EditFloor400Response();

            if (data.hasOwnProperty('error')) {
                obj['error'] = EditFloor400ResponseError.constructFromObject(data['error']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EditFloor400Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EditFloor400Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EditFloor400Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `error`
        if (data['error']) { // data not null
          EditFloor400ResponseError.validateJSON(data['error']);
        }

        return true;
    }


}

EditFloor400Response.RequiredProperties = ["error"];

/**
 * @member {module:model/EditFloor400ResponseError} error
 */
EditFloor400Response.prototype['error'] = undefined;






export default EditFloor400Response;

