/**
 * Floor Memory
 * The set APIs are used to develop Floor pds which can be used as their personal assistants. This set of APIs are divided into two parts.
 * - Memory and
 * - Registration. The developer has two ways of using the APIs for the app development. Developer can choose to the Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ipomo.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BlockDetails from './BlockDetails';
import Media from './Media';

/**
 * The GetFloorInformation200Response model module.
 * @module model/GetFloorInformation200Response
 * @version 1.0.9
 */
class GetFloorInformation200Response {
    /**
     * Constructs a new <code>GetFloorInformation200Response</code>.
     * @alias module:model/GetFloorInformation200Response
     * @param floorId {String} Pod floor ID
     * @param title {String} Title
     * @param floorUid {String} Unique numeric ID of the pod floor
     * @param isOwner {String} Is the user Owner
     * @param floorType {String} Type of floor (POD, PUBLIC or PRIVATE)
     */
    constructor(floorId, title, floorUid, isOwner, floorType) { 
        
        GetFloorInformation200Response.initialize(this, floorId, title, floorUid, isOwner, floorType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, floorId, title, floorUid, isOwner, floorType) { 
        obj['floor_id'] = floorId;
        obj['title'] = title;
        obj['floor_uid'] = floorUid;
        obj['is_owner'] = isOwner;
        obj['floor_type'] = floorType;
    }

    /**
     * Constructs a <code>GetFloorInformation200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetFloorInformation200Response} obj Optional instance to populate.
     * @return {module:model/GetFloorInformation200Response} The populated <code>GetFloorInformation200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetFloorInformation200Response();

            if (data.hasOwnProperty('floor_id')) {
                obj['floor_id'] = ApiClient.convertToType(data['floor_id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = ApiClient.convertToType(data['details'], 'String');
            }
            if (data.hasOwnProperty('floor_uid')) {
                obj['floor_uid'] = ApiClient.convertToType(data['floor_uid'], 'String');
            }
            if (data.hasOwnProperty('blocks')) {
                obj['blocks'] = ApiClient.convertToType(data['blocks'], [BlockDetails]);
            }
            if (data.hasOwnProperty('avatar')) {
                obj['avatar'] = Media.constructFromObject(data['avatar']);
            }
            if (data.hasOwnProperty('is_owner')) {
                obj['is_owner'] = ApiClient.convertToType(data['is_owner'], 'String');
            }
            if (data.hasOwnProperty('floor_type')) {
                obj['floor_type'] = ApiClient.convertToType(data['floor_type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetFloorInformation200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetFloorInformation200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetFloorInformation200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['floor_id'] && !(typeof data['floor_id'] === 'string' || data['floor_id'] instanceof String)) {
            throw new Error("Expected the field `floor_id` to be a primitive type in the JSON string but got " + data['floor_id']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['details'] && !(typeof data['details'] === 'string' || data['details'] instanceof String)) {
            throw new Error("Expected the field `details` to be a primitive type in the JSON string but got " + data['details']);
        }
        // ensure the json data is a string
        if (data['floor_uid'] && !(typeof data['floor_uid'] === 'string' || data['floor_uid'] instanceof String)) {
            throw new Error("Expected the field `floor_uid` to be a primitive type in the JSON string but got " + data['floor_uid']);
        }
        if (data['blocks']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['blocks'])) {
                throw new Error("Expected the field `blocks` to be an array in the JSON data but got " + data['blocks']);
            }
            // validate the optional field `blocks` (array)
            for (const item of data['blocks']) {
                BlockDetails.validateJSON(item);
            };
        }
        // validate the optional field `avatar`
        if (data['avatar']) { // data not null
          Media.validateJSON(data['avatar']);
        }
        // ensure the json data is a string
        if (data['is_owner'] && !(typeof data['is_owner'] === 'string' || data['is_owner'] instanceof String)) {
            throw new Error("Expected the field `is_owner` to be a primitive type in the JSON string but got " + data['is_owner']);
        }
        // ensure the json data is a string
        if (data['floor_type'] && !(typeof data['floor_type'] === 'string' || data['floor_type'] instanceof String)) {
            throw new Error("Expected the field `floor_type` to be a primitive type in the JSON string but got " + data['floor_type']);
        }

        return true;
    }


}

GetFloorInformation200Response.RequiredProperties = ["floor_id", "title", "floor_uid", "is_owner", "floor_type"];

/**
 * Pod floor ID
 * @member {String} floor_id
 */
GetFloorInformation200Response.prototype['floor_id'] = undefined;

/**
 * Title
 * @member {String} title
 */
GetFloorInformation200Response.prototype['title'] = undefined;

/**
 * Brief description about the Pod floor
 * @member {String} details
 */
GetFloorInformation200Response.prototype['details'] = undefined;

/**
 * Unique numeric ID of the pod floor
 * @member {String} floor_uid
 */
GetFloorInformation200Response.prototype['floor_uid'] = undefined;

/**
 * List of blocks
 * @member {Array.<module:model/BlockDetails>} blocks
 */
GetFloorInformation200Response.prototype['blocks'] = undefined;

/**
 * @member {module:model/Media} avatar
 */
GetFloorInformation200Response.prototype['avatar'] = undefined;

/**
 * Is the user Owner
 * @member {String} is_owner
 */
GetFloorInformation200Response.prototype['is_owner'] = undefined;

/**
 * Type of floor (POD, PUBLIC or PRIVATE)
 * @member {String} floor_type
 */
GetFloorInformation200Response.prototype['floor_type'] = undefined;






export default GetFloorInformation200Response;

