/**
 * Floor Memory
 * The set APIs are used to develop Floor pds which can be used as their personal assistants. This set of APIs are divided into two parts.
 * - Memory and
 * - Registration. The developer has two ways of using the APIs for the app development. Developer can choose to the Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ipomo.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Media from './Media';

/**
 * The GetRecentEvents200ResponseItemsInnerAuthor model module.
 * @module model/GetRecentEvents200ResponseItemsInnerAuthor
 * @version 1.0.7
 */
class GetRecentEvents200ResponseItemsInnerAuthor {
    /**
     * Constructs a new <code>GetRecentEvents200ResponseItemsInnerAuthor</code>.
     * Author details
     * @alias module:model/GetRecentEvents200ResponseItemsInnerAuthor
     */
    constructor() { 
        
        GetRecentEvents200ResponseItemsInnerAuthor.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetRecentEvents200ResponseItemsInnerAuthor</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetRecentEvents200ResponseItemsInnerAuthor} obj Optional instance to populate.
     * @return {module:model/GetRecentEvents200ResponseItemsInnerAuthor} The populated <code>GetRecentEvents200ResponseItemsInnerAuthor</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetRecentEvents200ResponseItemsInnerAuthor();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('floor_id')) {
                obj['floor_id'] = ApiClient.convertToType(data['floor_id'], 'String');
            }
            if (data.hasOwnProperty('avatar')) {
                obj['avatar'] = Media.constructFromObject(data['avatar']);
            }
            if (data.hasOwnProperty('floor_uid')) {
                obj['floor_uid'] = ApiClient.convertToType(data['floor_uid'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetRecentEvents200ResponseItemsInnerAuthor</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetRecentEvents200ResponseItemsInnerAuthor</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['floor_id'] && !(typeof data['floor_id'] === 'string' || data['floor_id'] instanceof String)) {
            throw new Error("Expected the field `floor_id` to be a primitive type in the JSON string but got " + data['floor_id']);
        }
        // validate the optional field `avatar`
        if (data['avatar']) { // data not null
          Media.validateJSON(data['avatar']);
        }
        // ensure the json data is a string
        if (data['floor_uid'] && !(typeof data['floor_uid'] === 'string' || data['floor_uid'] instanceof String)) {
            throw new Error("Expected the field `floor_uid` to be a primitive type in the JSON string but got " + data['floor_uid']);
        }

        return true;
    }


}



/**
 * Name of the author
 * @member {String} name
 */
GetRecentEvents200ResponseItemsInnerAuthor.prototype['name'] = undefined;

/**
 * Profile floor of the auther
 * @member {String} floor_id
 */
GetRecentEvents200ResponseItemsInnerAuthor.prototype['floor_id'] = undefined;

/**
 * @member {module:model/Media} avatar
 */
GetRecentEvents200ResponseItemsInnerAuthor.prototype['avatar'] = undefined;

/**
 * Unique 13 digit id of the profile floor
 * @member {String} floor_uid
 */
GetRecentEvents200ResponseItemsInnerAuthor.prototype['floor_uid'] = undefined;






export default GetRecentEvents200ResponseItemsInnerAuthor;

