/**
 * Floor Memory
 * The set APIs are used to develop Floor pds which can be used as their personal assistants. This set of APIs are divided into two parts.
 * - Memory and
 * - Registration. The developer has two ways of using the APIs for the app development. Developer can choose to the Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ipomo.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetRecentEvents200ResponseItemsInnerAuthor from './GetRecentEvents200ResponseItemsInnerAuthor';
import Media from './Media';

/**
 * The GetRecentEvents200ResponseItemsInner model module.
 * @module model/GetRecentEvents200ResponseItemsInner
 * @version 1.0.9
 */
class GetRecentEvents200ResponseItemsInner {
    /**
     * Constructs a new <code>GetRecentEvents200ResponseItemsInner</code>.
     * Each post item
     * @alias module:model/GetRecentEvents200ResponseItemsInner
     */
    constructor() { 
        
        GetRecentEvents200ResponseItemsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetRecentEvents200ResponseItemsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetRecentEvents200ResponseItemsInner} obj Optional instance to populate.
     * @return {module:model/GetRecentEvents200ResponseItemsInner} The populated <code>GetRecentEvents200ResponseItemsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetRecentEvents200ResponseItemsInner();

            if (data.hasOwnProperty('event_id')) {
                obj['event_id'] = ApiClient.convertToType(data['event_id'], 'String');
            }
            if (data.hasOwnProperty('block_type')) {
                obj['block_type'] = ApiClient.convertToType(data['block_type'], 'String');
            }
            if (data.hasOwnProperty('author')) {
                obj['author'] = GetRecentEvents200ResponseItemsInnerAuthor.constructFromObject(data['author']);
            }
            if (data.hasOwnProperty('media')) {
                obj['media'] = ApiClient.convertToType(data['media'], [Media]);
            }
            if (data.hasOwnProperty('floor_uid')) {
                obj['floor_uid'] = ApiClient.convertToType(data['floor_uid'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('created_at_ms')) {
                obj['created_at_ms'] = ApiClient.convertToType(data['created_at_ms'], 'String');
            }
            if (data.hasOwnProperty('block_id')) {
                obj['block_id'] = ApiClient.convertToType(data['block_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetRecentEvents200ResponseItemsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetRecentEvents200ResponseItemsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['event_id'] && !(typeof data['event_id'] === 'string' || data['event_id'] instanceof String)) {
            throw new Error("Expected the field `event_id` to be a primitive type in the JSON string but got " + data['event_id']);
        }
        // ensure the json data is a string
        if (data['block_type'] && !(typeof data['block_type'] === 'string' || data['block_type'] instanceof String)) {
            throw new Error("Expected the field `block_type` to be a primitive type in the JSON string but got " + data['block_type']);
        }
        // validate the optional field `author`
        if (data['author']) { // data not null
          GetRecentEvents200ResponseItemsInnerAuthor.validateJSON(data['author']);
        }
        if (data['media']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['media'])) {
                throw new Error("Expected the field `media` to be an array in the JSON data but got " + data['media']);
            }
            // validate the optional field `media` (array)
            for (const item of data['media']) {
                Media.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['floor_uid'] && !(typeof data['floor_uid'] === 'string' || data['floor_uid'] instanceof String)) {
            throw new Error("Expected the field `floor_uid` to be a primitive type in the JSON string but got " + data['floor_uid']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['text'] && !(typeof data['text'] === 'string' || data['text'] instanceof String)) {
            throw new Error("Expected the field `text` to be a primitive type in the JSON string but got " + data['text']);
        }
        // ensure the json data is a string
        if (data['created_at_ms'] && !(typeof data['created_at_ms'] === 'string' || data['created_at_ms'] instanceof String)) {
            throw new Error("Expected the field `created_at_ms` to be a primitive type in the JSON string but got " + data['created_at_ms']);
        }
        // ensure the json data is a string
        if (data['block_id'] && !(typeof data['block_id'] === 'string' || data['block_id'] instanceof String)) {
            throw new Error("Expected the field `block_id` to be a primitive type in the JSON string but got " + data['block_id']);
        }

        return true;
    }


}



/**
 *  Post ID
 * @member {String} event_id
 */
GetRecentEvents200ResponseItemsInner.prototype['event_id'] = undefined;

/**
 * Block Type
 * @member {String} block_type
 */
GetRecentEvents200ResponseItemsInner.prototype['block_type'] = undefined;

/**
 * @member {module:model/GetRecentEvents200ResponseItemsInnerAuthor} author
 */
GetRecentEvents200ResponseItemsInner.prototype['author'] = undefined;

/**
 * Any media attached
 * @member {Array.<module:model/Media>} media
 */
GetRecentEvents200ResponseItemsInner.prototype['media'] = undefined;

/**
 * 13 digit ID of the floor in which the post is residing
 * @member {String} floor_uid
 */
GetRecentEvents200ResponseItemsInner.prototype['floor_uid'] = undefined;

/**
 * Post title
 * @member {String} title
 */
GetRecentEvents200ResponseItemsInner.prototype['title'] = undefined;

/**
 * Post details
 * @member {String} text
 */
GetRecentEvents200ResponseItemsInner.prototype['text'] = undefined;

/**
 * Created time in milli seconds
 * @member {String} created_at_ms
 */
GetRecentEvents200ResponseItemsInner.prototype['created_at_ms'] = undefined;

/**
 * Numeric ID of the block
 * @member {String} block_id
 */
GetRecentEvents200ResponseItemsInner.prototype['block_id'] = undefined;






export default GetRecentEvents200ResponseItemsInner;

