/**
 * Floor Memory
 * The set APIs are used to develop Floor pds which can be used as their personal assistants. This set of APIs are divided into two parts.
 * - Memory and
 * - Registration. The developer has two ways of using the APIs for the app development. Developer can choose to the Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ipomo.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Remaining from './Remaining';
import SignInWithEmail200ResponseProfileAvatar from './SignInWithEmail200ResponseProfileAvatar';

/**
 * The SignInWithEmail200ResponseProfile model module.
 * @module model/SignInWithEmail200ResponseProfile
 * @version 1.0.19
 */
class SignInWithEmail200ResponseProfile {
    /**
     * Constructs a new <code>SignInWithEmail200ResponseProfile</code>.
     * User profile details
     * @alias module:model/SignInWithEmail200ResponseProfile
     * @param floorId {String} Associated floor ID
     * @param FID {String} Unique ID of floor
     * @param userId {String} Unique User ID
     */
    constructor(floorId, FID, userId) { 
        
        SignInWithEmail200ResponseProfile.initialize(this, floorId, FID, userId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, floorId, FID, userId) { 
        obj['floor_id'] = floorId;
        obj['FID'] = FID;
        obj['user_id'] = userId;
    }

    /**
     * Constructs a <code>SignInWithEmail200ResponseProfile</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SignInWithEmail200ResponseProfile} obj Optional instance to populate.
     * @return {module:model/SignInWithEmail200ResponseProfile} The populated <code>SignInWithEmail200ResponseProfile</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SignInWithEmail200ResponseProfile();

            if (data.hasOwnProperty('floor_id')) {
                obj['floor_id'] = ApiClient.convertToType(data['floor_id'], 'String');
            }
            if (data.hasOwnProperty('floors')) {
                obj['floors'] = Remaining.constructFromObject(data['floors']);
            }
            if (data.hasOwnProperty('blocks')) {
                obj['blocks'] = Remaining.constructFromObject(data['blocks']);
            }
            if (data.hasOwnProperty('FID')) {
                obj['FID'] = ApiClient.convertToType(data['FID'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('mobile_number')) {
                obj['mobile_number'] = ApiClient.convertToType(data['mobile_number'], 'String');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
            if (data.hasOwnProperty('avatar')) {
                obj['avatar'] = SignInWithEmail200ResponseProfileAvatar.constructFromObject(data['avatar']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SignInWithEmail200ResponseProfile</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SignInWithEmail200ResponseProfile</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SignInWithEmail200ResponseProfile.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['floor_id'] && !(typeof data['floor_id'] === 'string' || data['floor_id'] instanceof String)) {
            throw new Error("Expected the field `floor_id` to be a primitive type in the JSON string but got " + data['floor_id']);
        }
        // validate the optional field `floors`
        if (data['floors']) { // data not null
          Remaining.validateJSON(data['floors']);
        }
        // validate the optional field `blocks`
        if (data['blocks']) { // data not null
          Remaining.validateJSON(data['blocks']);
        }
        // ensure the json data is a string
        if (data['FID'] && !(typeof data['FID'] === 'string' || data['FID'] instanceof String)) {
            throw new Error("Expected the field `FID` to be a primitive type in the JSON string but got " + data['FID']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['mobile_number'] && !(typeof data['mobile_number'] === 'string' || data['mobile_number'] instanceof String)) {
            throw new Error("Expected the field `mobile_number` to be a primitive type in the JSON string but got " + data['mobile_number']);
        }
        // ensure the json data is a string
        if (data['user_id'] && !(typeof data['user_id'] === 'string' || data['user_id'] instanceof String)) {
            throw new Error("Expected the field `user_id` to be a primitive type in the JSON string but got " + data['user_id']);
        }
        // validate the optional field `avatar`
        if (data['avatar']) { // data not null
          SignInWithEmail200ResponseProfileAvatar.validateJSON(data['avatar']);
        }

        return true;
    }


}

SignInWithEmail200ResponseProfile.RequiredProperties = ["floor_id", "FID", "user_id"];

/**
 * Associated floor ID
 * @member {String} floor_id
 */
SignInWithEmail200ResponseProfile.prototype['floor_id'] = undefined;

/**
 * @member {module:model/Remaining} floors
 */
SignInWithEmail200ResponseProfile.prototype['floors'] = undefined;

/**
 * @member {module:model/Remaining} blocks
 */
SignInWithEmail200ResponseProfile.prototype['blocks'] = undefined;

/**
 * Unique ID of floor
 * @member {String} FID
 */
SignInWithEmail200ResponseProfile.prototype['FID'] = undefined;

/**
 * User Name
 * @member {String} name
 */
SignInWithEmail200ResponseProfile.prototype['name'] = undefined;

/**
 * Email ID
 * @member {String} email
 */
SignInWithEmail200ResponseProfile.prototype['email'] = undefined;

/**
 * Mobile number
 * @member {String} mobile_number
 */
SignInWithEmail200ResponseProfile.prototype['mobile_number'] = undefined;

/**
 * Unique User ID
 * @member {String} user_id
 */
SignInWithEmail200ResponseProfile.prototype['user_id'] = undefined;

/**
 * @member {module:model/SignInWithEmail200ResponseProfileAvatar} avatar
 */
SignInWithEmail200ResponseProfile.prototype['avatar'] = undefined;






export default SignInWithEmail200ResponseProfile;

