# coding: utf-8

"""
    Floor Memory

    The set APIs are used to develop Floor pds which can be used as their personal assistants. This set of APIs are divided into two parts.
    - Memory and
    - Registration. The developer has two ways of using the APIs for the app development. Developer can choose to the Registration APIs for using the existing xfloor infracture or can implement custom Registration process. In the case of custom registration process, the developer is bound to provide proper authentication mechanisms and then send the user information to xlfoor.

    The version of the OpenAPI document: 1.0.0
    Contact: contact@ipomo.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBytes, StrictStr
from typing import Optional, Tuple, Union
from typing_extensions import Annotated
from xfloor_memory_sdk.models.get_floor_information200_response import GetFloorInformation200Response

from xfloor_memory_sdk.api_client import ApiClient, RequestSerialized
from xfloor_memory_sdk.api_response import ApiResponse
from xfloor_memory_sdk.rest import RESTResponseType


class EditFloorApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def edit_floor(
        self,
        floor_id: StrictStr,
        user_id: Annotated[StrictStr, Field(description="User ID")],
        app_id: Annotated[StrictStr, Field(description="App ID")],
        logo_file: Annotated[Optional[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]]], Field(description="Floor avatar")] = None,
        title: Annotated[Optional[StrictStr], Field(description="Floor title")] = None,
        details: Annotated[Optional[StrictStr], Field(description="Floor decription")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GetFloorInformation200Response:
        """Edit floor

        This API updates an existing floor’s profile metadata using **multipart form data**. A floor **can be edited only by its owner**. If the authenticated user is **not the owner of the floor**, the request will be rejected, even if the user is a member or follower of the floor. The API allows the floor owner to update:
        * Floor **title** * Floor **details/description** * Floor **logo/avatar image** After a successful update, the API returns the **latest floor object**, including the updated avatar and the current list of blocks associated with the floor.
        
        ---
        
        ## Authorization Rules (Critical)
        * The caller **must be authenticated** * The caller **must be the owner of the floor** * Members, followers, or pod consumers **cannot** edit the floor * Ownership is validated internally using the authenticated user context > **Ownership is mandatory. There are no partial permissions for this API.**
        
        ---
        
        ## Content-Type `multipart/form-data`
        
        ---
        
        ## Request Body (Multipart Form Data)
        
        ### Form Fields | Field Name | Type | Required | Description |
        | ---------- | ------ | ------------ | ---------------------------------------- |
        | `fid` | String | Recommended* | Immutable internal floor ID |
        | `floor_id` | String | Optional* | Public / human-readable floor identifier |
        | `title` | String | Optional | New floor title |
        | `details` | String | Optional | New floor description |
        | `logo` | File | Optional | New floor logo image (PNG/JPG/WebP) |
        * At least **one floor identifier** (`fid` or `floor_id`) must be provided. **Best practice:** Use `fid` as the primary identifier.
        
        ---
        
        ## Update Rules
        * At least one of `title`, `details`, or `logo` must be present * Missing update fields result in a validation error * If `logo` is provided, the previous logo is replaced
        
        ---
        
        ## Response Format `application/json`
        
        ---
        
        ## Sample Success Response
        
        ```json { \"floor_id\": \"my_floor\", \"title\": \"daughter ouch upon yummy clamor\", \"details\": \"nostrud occaecat incididunt dolor adipisicing\", \"fid\": \"86\", \"blocks\": [ { \"bid\": \"83\", \"type\": \"pariatur\", \"title\": \"wherever demobilise acidly refute\" } ], \"avatar\": { \"url\": \"https://legal-availability.name/\", \"id\": \"98\" } } ```
        
        ---
        
        ## Error Responses (Authorization Focus)
        
        ### Not Floor Owner
        
        ```json { \"status\": \"ERROR\", \"message\": \"Only the floor owner can edit this floor\" } ```
        
        ### Floor Not Found
        
        ```json { \"status\": \"ERROR\", \"message\": \"Floor not found\" } ```
        
        ### No Update Fields
        
        ```json { \"status\": \"ERROR\", \"message\": \"No update fields provided\" } ```
        
        ---
        
        ## Notes
        * This API is **owner-only by design** * Pods and developer tools must operate using **owner credentials** * Blocks are returned for convenience but are **not editable through this API**
        
        ---

        :param floor_id:  (required)
        :type floor_id: str
        :param user_id: User ID (required)
        :type user_id: str
        :param app_id: App ID (required)
        :type app_id: str
        :param logo_file: Floor avatar
        :type logo_file: bytearray
        :param title: Floor title
        :type title: str
        :param details: Floor decription
        :type details: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._edit_floor_serialize(
            floor_id=floor_id,
            user_id=user_id,
            app_id=app_id,
            logo_file=logo_file,
            title=title,
            details=details,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetFloorInformation200Response",
            '400': "EditFloor400Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def edit_floor_with_http_info(
        self,
        floor_id: StrictStr,
        user_id: Annotated[StrictStr, Field(description="User ID")],
        app_id: Annotated[StrictStr, Field(description="App ID")],
        logo_file: Annotated[Optional[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]]], Field(description="Floor avatar")] = None,
        title: Annotated[Optional[StrictStr], Field(description="Floor title")] = None,
        details: Annotated[Optional[StrictStr], Field(description="Floor decription")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GetFloorInformation200Response]:
        """Edit floor

        This API updates an existing floor’s profile metadata using **multipart form data**. A floor **can be edited only by its owner**. If the authenticated user is **not the owner of the floor**, the request will be rejected, even if the user is a member or follower of the floor. The API allows the floor owner to update:
        * Floor **title** * Floor **details/description** * Floor **logo/avatar image** After a successful update, the API returns the **latest floor object**, including the updated avatar and the current list of blocks associated with the floor.
        
        ---
        
        ## Authorization Rules (Critical)
        * The caller **must be authenticated** * The caller **must be the owner of the floor** * Members, followers, or pod consumers **cannot** edit the floor * Ownership is validated internally using the authenticated user context > **Ownership is mandatory. There are no partial permissions for this API.**
        
        ---
        
        ## Content-Type `multipart/form-data`
        
        ---
        
        ## Request Body (Multipart Form Data)
        
        ### Form Fields | Field Name | Type | Required | Description |
        | ---------- | ------ | ------------ | ---------------------------------------- |
        | `fid` | String | Recommended* | Immutable internal floor ID |
        | `floor_id` | String | Optional* | Public / human-readable floor identifier |
        | `title` | String | Optional | New floor title |
        | `details` | String | Optional | New floor description |
        | `logo` | File | Optional | New floor logo image (PNG/JPG/WebP) |
        * At least **one floor identifier** (`fid` or `floor_id`) must be provided. **Best practice:** Use `fid` as the primary identifier.
        
        ---
        
        ## Update Rules
        * At least one of `title`, `details`, or `logo` must be present * Missing update fields result in a validation error * If `logo` is provided, the previous logo is replaced
        
        ---
        
        ## Response Format `application/json`
        
        ---
        
        ## Sample Success Response
        
        ```json { \"floor_id\": \"my_floor\", \"title\": \"daughter ouch upon yummy clamor\", \"details\": \"nostrud occaecat incididunt dolor adipisicing\", \"fid\": \"86\", \"blocks\": [ { \"bid\": \"83\", \"type\": \"pariatur\", \"title\": \"wherever demobilise acidly refute\" } ], \"avatar\": { \"url\": \"https://legal-availability.name/\", \"id\": \"98\" } } ```
        
        ---
        
        ## Error Responses (Authorization Focus)
        
        ### Not Floor Owner
        
        ```json { \"status\": \"ERROR\", \"message\": \"Only the floor owner can edit this floor\" } ```
        
        ### Floor Not Found
        
        ```json { \"status\": \"ERROR\", \"message\": \"Floor not found\" } ```
        
        ### No Update Fields
        
        ```json { \"status\": \"ERROR\", \"message\": \"No update fields provided\" } ```
        
        ---
        
        ## Notes
        * This API is **owner-only by design** * Pods and developer tools must operate using **owner credentials** * Blocks are returned for convenience but are **not editable through this API**
        
        ---

        :param floor_id:  (required)
        :type floor_id: str
        :param user_id: User ID (required)
        :type user_id: str
        :param app_id: App ID (required)
        :type app_id: str
        :param logo_file: Floor avatar
        :type logo_file: bytearray
        :param title: Floor title
        :type title: str
        :param details: Floor decription
        :type details: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._edit_floor_serialize(
            floor_id=floor_id,
            user_id=user_id,
            app_id=app_id,
            logo_file=logo_file,
            title=title,
            details=details,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetFloorInformation200Response",
            '400': "EditFloor400Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def edit_floor_without_preload_content(
        self,
        floor_id: StrictStr,
        user_id: Annotated[StrictStr, Field(description="User ID")],
        app_id: Annotated[StrictStr, Field(description="App ID")],
        logo_file: Annotated[Optional[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]]], Field(description="Floor avatar")] = None,
        title: Annotated[Optional[StrictStr], Field(description="Floor title")] = None,
        details: Annotated[Optional[StrictStr], Field(description="Floor decription")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Edit floor

        This API updates an existing floor’s profile metadata using **multipart form data**. A floor **can be edited only by its owner**. If the authenticated user is **not the owner of the floor**, the request will be rejected, even if the user is a member or follower of the floor. The API allows the floor owner to update:
        * Floor **title** * Floor **details/description** * Floor **logo/avatar image** After a successful update, the API returns the **latest floor object**, including the updated avatar and the current list of blocks associated with the floor.
        
        ---
        
        ## Authorization Rules (Critical)
        * The caller **must be authenticated** * The caller **must be the owner of the floor** * Members, followers, or pod consumers **cannot** edit the floor * Ownership is validated internally using the authenticated user context > **Ownership is mandatory. There are no partial permissions for this API.**
        
        ---
        
        ## Content-Type `multipart/form-data`
        
        ---
        
        ## Request Body (Multipart Form Data)
        
        ### Form Fields | Field Name | Type | Required | Description |
        | ---------- | ------ | ------------ | ---------------------------------------- |
        | `fid` | String | Recommended* | Immutable internal floor ID |
        | `floor_id` | String | Optional* | Public / human-readable floor identifier |
        | `title` | String | Optional | New floor title |
        | `details` | String | Optional | New floor description |
        | `logo` | File | Optional | New floor logo image (PNG/JPG/WebP) |
        * At least **one floor identifier** (`fid` or `floor_id`) must be provided. **Best practice:** Use `fid` as the primary identifier.
        
        ---
        
        ## Update Rules
        * At least one of `title`, `details`, or `logo` must be present * Missing update fields result in a validation error * If `logo` is provided, the previous logo is replaced
        
        ---
        
        ## Response Format `application/json`
        
        ---
        
        ## Sample Success Response
        
        ```json { \"floor_id\": \"my_floor\", \"title\": \"daughter ouch upon yummy clamor\", \"details\": \"nostrud occaecat incididunt dolor adipisicing\", \"fid\": \"86\", \"blocks\": [ { \"bid\": \"83\", \"type\": \"pariatur\", \"title\": \"wherever demobilise acidly refute\" } ], \"avatar\": { \"url\": \"https://legal-availability.name/\", \"id\": \"98\" } } ```
        
        ---
        
        ## Error Responses (Authorization Focus)
        
        ### Not Floor Owner
        
        ```json { \"status\": \"ERROR\", \"message\": \"Only the floor owner can edit this floor\" } ```
        
        ### Floor Not Found
        
        ```json { \"status\": \"ERROR\", \"message\": \"Floor not found\" } ```
        
        ### No Update Fields
        
        ```json { \"status\": \"ERROR\", \"message\": \"No update fields provided\" } ```
        
        ---
        
        ## Notes
        * This API is **owner-only by design** * Pods and developer tools must operate using **owner credentials** * Blocks are returned for convenience but are **not editable through this API**
        
        ---

        :param floor_id:  (required)
        :type floor_id: str
        :param user_id: User ID (required)
        :type user_id: str
        :param app_id: App ID (required)
        :type app_id: str
        :param logo_file: Floor avatar
        :type logo_file: bytearray
        :param title: Floor title
        :type title: str
        :param details: Floor decription
        :type details: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._edit_floor_serialize(
            floor_id=floor_id,
            user_id=user_id,
            app_id=app_id,
            logo_file=logo_file,
            title=title,
            details=details,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetFloorInformation200Response",
            '400': "EditFloor400Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _edit_floor_serialize(
        self,
        floor_id,
        user_id,
        app_id,
        logo_file,
        title,
        details,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if floor_id is not None:
            _path_params['floor_id'] = floor_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        if user_id is not None:
            _form_params.append(('user_id', user_id))
        if app_id is not None:
            _form_params.append(('app_id', app_id))
        if logo_file is not None:
            _files['logo_file'] = logo_file
        if title is not None:
            _form_params.append(('title', title))
        if details is not None:
            _form_params.append(('details', details))
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'multipart/form-data'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'bearer'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/api/memory/edit/floor/{floor_id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


